import type { Language } from "./i18n";

/**
 * Os textos da área de IA: o botão do topo, a central de modelos, o diálogo de
 * pré-anotação e o resumo de cada execução.
 *
 * Ficam fora de `i18n.ts` porque formam um vocabulário próprio — Assistido e
 * Automático, Nativo e Contêiner — que precisa ser dito do mesmo jeito em todas
 * as telas. Juntos aqui, uma troca de palavra muda tudo de uma vez.
 *
 * Regra de escrita: direto e curto. Rótulo diz o que é, dica diz o que fazer,
 * numa frase. O porquê fica nos comentários do código e na documentação.
 *
 * A tipagem é a mesma do resto: cada idioma precisa ter todas as chaves do
 * português, e o compilador recusa o que faltar.
 */
const pt = {
  aiButton: "IA",
  aiHintSam: "Assistido: {model}",
  aiHintRuntime: "Nativo: {model}",
  aiHintContainers: "Contêineres no ar: {n}",
  aiHintNone: "Nenhum modelo conectado. Clique para configurar.",
  preAnnotate: "Pré-anotar",
  preAnnotateHint: "A IA anota a imagem ou o projeto",

  hubTitle: "Modelos de IA",
  hubSubtitle: "Assistido: você aponta, a IA recorta. Automático: a IA anota sozinha.",
  tabAssisted: "Assistido",
  tabAssistedHint: "Você aponta, a IA recorta",
  tabAutomatic: "Automático",
  tabAutomaticHint: "A IA anota sozinha",
  tabConnections: "Conexões",
  tabConnectionsHint: "O que está rodando",
  close: "Fechar",

  listStartHere: "Comece aqui",
  familySam2: "SAM 2.1 · recomendado",
  familyMedsam2: "Imagem médica",
  familySam3: "SAM 3 · conceitos",
  inUse: "em uso",
  installed: "instalado",
  recommended: "Recomendado",
  experimental: "Experimental",
  modelsList: "Modelos disponíveis",

  howTitle: "Como funciona",
  howHint: "Onde sua imagem é processada",
  howIntro: "Tudo roda no seu computador. Nenhuma imagem vai para a internet.",
  howFindsTitle: "A página só encontra programas já abertos",
  howFindsBody: "O navegador não pode iniciar programas. Deixe a janela do instalador aberta; no Linux, o serviço de usuário faz isso por você.",
  howModesTitle: "Assistido e Automático são independentes",
  howModesBody: "Assistido recorta o objeto que você indica. Automático anota a imagem inteira. Um não altera o resultado do outro.",
  howPrivacyTitle: "Privacidade",
  howPrivacyBody: "Imagens e prompts não saem do computador. Contêineres só são aceitos em 127.0.0.1 ou localhost.",

  autoGuideTitle: "Qual escolher",
  autoGuideHint: "Nativo ou Contêiner",
  autoNativeSection: "Nativos",
  autoNativeOffline: "Runtime desligado",
  autoNativeOfflineHint: "Ver como conectar",
  autoMineSection: "Meus modelos (Contêiner)",
  autoMineEmpty: "Nenhum contêiner",
  autoAddModel: "Adicionar meu modelo",
  autoAddModelHint: "Docker: passo a passo",
  badgeNative: "Nativo",
  badgeContainer: "Contêiner",
  stateUp: "no ar",
  stateDown: "parado",

  guideIntro: "No Automático, o modelo anota a imagem sozinho. Há dois tipos:",
  guideNativeTitle: "Nativo",
  guideNativeBody: "Feito para o Poligome. Aguenta imagens enormes, mostra o resultado enquanto roda e tem ajustes na tela.",
  guideContainerTitle: "Contêiner",
  guideContainerBody: "O seu modelo, num Docker. Fácil de plugar, mas recebe a imagem inteira e só responde no fim.",
  guideColumnNeed: "Recurso",
  guideRowLarge: "Imagens enormes",
  guideRowRegion: "Só uma região",
  guideRowParams: "Ajustes na tela",
  guideRowLive: "Resultado ao vivo",
  guideRowBatch: "Projeto inteiro",
  guideRowEffort: "Para plugar",
  guideYes: "Sim",
  guideNo: "Não",
  guideLargeContainer: "Até 16 MP",
  guideEffortNative: "Implementar o protocolo",
  guideEffortContainer: "Trocar uma função",
  guideRule: "Já tem um modelo? Contêiner. Imagens enormes ou quer ajustar sem código? Nativo.",
  guideReview: "Toda pré-anotação pode ser desfeita de uma vez.",

  nativeServedBy: "Rodando no Poligome Runtime ({endpoint}).",
  nativeVersion: "Versão",
  nativeLicense: "Licença",
  nativeProduces: "Produz",
  nativeAccepts: "Aceita",
  nativeLarge: "Imagens grandes",
  nativeLargeValue: "Em partes de até {px} px",
  nativeLargeWhole: "Imagem inteira",
  nativeParams: "Ajustes",
  nativeNoParams: "Nenhum",
  nativeNone: "—",
  geomBox: "caixas",
  geomPolygon: "polígonos",
  geomPolyline: "linhas",
  geomKeypoint: "pontos",
  geomMask: "máscaras",
  promptRegion: "região",
  promptPoints: "pontos",
  promptBox: "caixa",
  promptText: "texto",
  runtimeOfflineTitle: "Nenhum modelo nativo",
  runtimeOfflineBody: "Inicie o Poligome Runtime. O modelo dele aparece aqui.",
  runtimeOfflineAddress: "Procurando em {endpoint}. Outro endereço? Mude em Conexões.",
  openConnections: "Abrir Conexões",
  usePreannotate: "Pré-anotar com este modelo",

  containerUp: "no ar",
  containerDown: "parado",
  containerImage: "imagem {name}",
  containerLimits: "Limitações",
  containerClasses: "Classes",
  containerParams: "Parâmetros",
  containerEnv: "Ambiente",
  containerLastRun: "Última execução",
  annotationOne: "{n} anotação",
  annotationMany: "{n} anotações",
  fieldName: "Nome",
  fieldPort: "Porta",
  fieldNote: "Nota",
  fieldNotePlaceholder: "Para que serve, o que revisar.",
  cancel: "Cancelar",
  save: "Salvar",
  saveFailed: "Não foi possível salvar: {detail}",
  editContainer: "Editar",
  removeContainer: "Remover da lista (o contêiner continua no Docker)",
  containerStoppedHint: "Contêiner parado. Inicie com o comando start da CLI.",
  byomNoMetadataReady: "Sem descrição. Rode uma vez para ver o que ele produz.",
  byomNoMetadataDown: "Sem descrição. Inicie o contêiner para ver as classes.",
  byomDeclares: "{n} classes: {list}.",
  byomDeclaresOne: "1 classe: {list}.",
  byomObserved: "Última execução: {n} classes ({list}).",
  byomObservedOne: "Última execução: 1 classe ({list}).",
  byomExports: "Produz {list}.",
  byomLastImage: "Última imagem: {count}.",
  listAnd: "e",

  connIntro: "Programas no seu computador que a IA usa.",
  connConnectorTitle: "Conector local",
  connConnectorRole: "Para o Assistido (SAM) e os Contêineres.",
  connRuntimeTitle: "Poligome Runtime",
  connRuntimeRole: "Para os modelos Nativos.",
  connContainersTitle: "Contêineres",
  connContainersRole: "Seus modelos em Docker.",
  connUp: "Conectado",
  connDown: "Desligado",
  connChecking: "Verificando…",
  connServing: "Rodando {model}",
  connHost: "em {host}",
  connAddress: "Endereço",
  connRetry: "Verificar",
  connContainersCount: "{up} de {total} no ar",
  connContainersNone: "Nenhum contêiner.",
  connContainersNeedConnector: "Precisa do conector ligado.",
  connConnectorHow: "Instale pela aba Assistido.",
  connConnectorHowButton: "Instalar",
  connContainersHowButton: "Adicionar",
  connPortClash: "A porta 7861 também é do conversor de COG. Se os dois rodarem, mude uma das portas.",

  paSubtitle: "A IA anota. Você revisa ou desfaz.",
  paModel: "Modelo",
  paWhere: "Onde",
  paParams: "Ajustes",
  paScopeImage: "Esta imagem",
  paScopeRegion: "Região selecionada",
  paScopeAll: "Todas ({n})",
  paRegionNeedsBox: "Selecione uma caixa para usar como região.",
  paRegionNativeOnly: "Região: só modelos Nativos.",
  paLargeImage: "Imagem de {mp} MP. Contêineres aceitam até 16 MP. Use um modelo Nativo.",
  paNoModels: "Nenhum modelo automático",
  paNoModelsHint: "Inicie o Poligome Runtime ou um contêiner.",
  paOpenHub: "Abrir modelos de IA",
  paStopped: "parado",
  paCapNative: "imagens grandes · região · ajustes",
  paCapContainer: "imagem inteira",
  paNoImage: "Abra uma imagem primeiro.",
  paBusy: "Já há uma pré-anotação rodando.",

  progressLabel: "Pré-anotando · {model}",
  progressImage: "imagem {i}/{n}",
  progressTiles: "parte {done}/{total}",
  progressCancel: "Cancelar",

  sumDone: "{count} criadas",
  sumDoneImages: "{count} criadas em {images} imagens",
  sumCanceled: "Cancelado · {count} mantidas",
  sumFailed: "Falhou em: {names}.",
  sumReview: "Revise antes de exportar.",
  sumKeep: "Manter",
  sumUndo: "Desfazer",
  sumUndone: "Pré-anotação desfeita: {count} removidas.",
  sumNone: "{model} não encontrou nada.",
  sumReplaced: "{n} anteriores substituídas.",

  runRegion: "{model}: região {w}×{h}…",
  runWorking: "{model}: anotando…",
  runNoCoco: "{model}: resposta sem COCO.",
  runHttp: "{model}: HTTP {status}",
  runRuntimeError: "Runtime: {detail}",
  runRuntimeUnreachable: "Poligome Runtime não respondeu. Veja em Modelos de IA › Conexões.",
  runConnectorUnreachable: "Conector local não respondeu. Veja em Modelos de IA › Conexões.",
};

export type AiCopyKey = keyof typeof pt;
export type AiCopy = Record<AiCopyKey, string>;

const en: AiCopy = {
  aiButton: "AI",
  aiHintSam: "Assisted: {model}",
  aiHintRuntime: "Native: {model}",
  aiHintContainers: "Containers up: {n}",
  aiHintNone: "No model connected. Click to set up.",
  preAnnotate: "Pre-annotate",
  preAnnotateHint: "The AI annotates the image or the project",

  hubTitle: "AI models",
  hubSubtitle: "Assisted: you point, the AI cuts out. Automatic: the AI annotates on its own.",
  tabAssisted: "Assisted",
  tabAssistedHint: "You point, the AI cuts out",
  tabAutomatic: "Automatic",
  tabAutomaticHint: "The AI annotates on its own",
  tabConnections: "Connections",
  tabConnectionsHint: "What is running",
  close: "Close",

  listStartHere: "Start here",
  familySam2: "SAM 2.1 · recommended",
  familyMedsam2: "Medical imaging",
  familySam3: "SAM 3 · concepts",
  inUse: "in use",
  installed: "installed",
  recommended: "Recommended",
  experimental: "Experimental",
  modelsList: "Available models",

  howTitle: "How it works",
  howHint: "Where your image is processed",
  howIntro: "Everything runs on your computer. No image goes online.",
  howFindsTitle: "The page only finds programs already open",
  howFindsBody: "Browsers cannot start programs. Keep the installer window open; on Linux, the user service does it for you.",
  howModesTitle: "Assisted and Automatic are independent",
  howModesBody: "Assisted cuts out the object you point at. Automatic annotates the whole image. Neither changes the other's result.",
  howPrivacyTitle: "Privacy",
  howPrivacyBody: "Images and prompts never leave the computer. Containers are only accepted on 127.0.0.1 or localhost.",

  autoGuideTitle: "Which to choose",
  autoGuideHint: "Native or Container",
  autoNativeSection: "Native",
  autoNativeOffline: "Runtime off",
  autoNativeOfflineHint: "See how to connect",
  autoMineSection: "My models (Container)",
  autoMineEmpty: "No containers",
  autoAddModel: "Add my model",
  autoAddModelHint: "Docker: step by step",
  badgeNative: "Native",
  badgeContainer: "Container",
  stateUp: "up",
  stateDown: "stopped",

  guideIntro: "In Automatic, the model annotates the image on its own. There are two kinds:",
  guideNativeTitle: "Native",
  guideNativeBody: "Built for Poligome. Handles huge images, shows results as it runs and has on-screen settings.",
  guideContainerTitle: "Container",
  guideContainerBody: "Your own model, in Docker. Easy to plug in, but it gets the whole image and answers only at the end.",
  guideColumnNeed: "Feature",
  guideRowLarge: "Huge images",
  guideRowRegion: "Just a region",
  guideRowParams: "On-screen settings",
  guideRowLive: "Live results",
  guideRowBatch: "Whole project",
  guideRowEffort: "To plug in",
  guideYes: "Yes",
  guideNo: "No",
  guideLargeContainer: "Up to 16 MP",
  guideEffortNative: "Implement the protocol",
  guideEffortContainer: "Replace one function",
  guideRule: "Already have a model? Container. Huge images, or want settings without code? Native.",
  guideReview: "Every pre-annotation can be undone in one step.",

  nativeServedBy: "Running on Poligome Runtime ({endpoint}).",
  nativeVersion: "Version",
  nativeLicense: "License",
  nativeProduces: "Produces",
  nativeAccepts: "Accepts",
  nativeLarge: "Large images",
  nativeLargeValue: "In parts up to {px} px",
  nativeLargeWhole: "Whole image",
  nativeParams: "Settings",
  nativeNoParams: "None",
  nativeNone: "—",
  geomBox: "boxes",
  geomPolygon: "polygons",
  geomPolyline: "lines",
  geomKeypoint: "points",
  geomMask: "masks",
  promptRegion: "region",
  promptPoints: "points",
  promptBox: "box",
  promptText: "text",
  runtimeOfflineTitle: "No native model",
  runtimeOfflineBody: "Start Poligome Runtime. Its model shows up here.",
  runtimeOfflineAddress: "Looking at {endpoint}. Different address? Change it in Connections.",
  openConnections: "Open Connections",
  usePreannotate: "Pre-annotate with this model",

  containerUp: "up",
  containerDown: "stopped",
  containerImage: "image {name}",
  containerLimits: "Limitations",
  containerClasses: "Classes",
  containerParams: "Parameters",
  containerEnv: "Environment",
  containerLastRun: "Last run",
  annotationOne: "{n} annotation",
  annotationMany: "{n} annotations",
  fieldName: "Name",
  fieldPort: "Port",
  fieldNote: "Note",
  fieldNotePlaceholder: "What it is for, what to check.",
  cancel: "Cancel",
  save: "Save",
  saveFailed: "Could not save: {detail}",
  editContainer: "Edit",
  removeContainer: "Remove from the list (the container stays in Docker)",
  containerStoppedHint: "Container stopped. Start it with the CLI start command.",
  byomNoMetadataReady: "No description. Run it once to see what it produces.",
  byomNoMetadataDown: "No description. Start the container to see its classes.",
  byomDeclares: "{n} classes: {list}.",
  byomDeclaresOne: "1 class: {list}.",
  byomObserved: "Last run: {n} classes ({list}).",
  byomObservedOne: "Last run: 1 class ({list}).",
  byomExports: "Produces {list}.",
  byomLastImage: "Last image: {count}.",
  listAnd: "and",

  connIntro: "Programs on your computer that the AI uses.",
  connConnectorTitle: "Local connector",
  connConnectorRole: "For Assisted (SAM) and Containers.",
  connRuntimeTitle: "Poligome Runtime",
  connRuntimeRole: "For Native models.",
  connContainersTitle: "Containers",
  connContainersRole: "Your models in Docker.",
  connUp: "Connected",
  connDown: "Off",
  connChecking: "Checking…",
  connServing: "Running {model}",
  connHost: "on {host}",
  connAddress: "Address",
  connRetry: "Check",
  connContainersCount: "{up} of {total} up",
  connContainersNone: "No containers.",
  connContainersNeedConnector: "Needs the connector running.",
  connConnectorHow: "Install it from the Assisted tab.",
  connConnectorHowButton: "Install",
  connContainersHowButton: "Add",
  connPortClash: "Port 7861 is also the COG converter's. If both run, change one of the ports.",

  paSubtitle: "The AI annotates. You review or undo.",
  paModel: "Model",
  paWhere: "Where",
  paParams: "Settings",
  paScopeImage: "This image",
  paScopeRegion: "Selected region",
  paScopeAll: "All ({n})",
  paRegionNeedsBox: "Select a box to use as the region.",
  paRegionNativeOnly: "Region: Native models only.",
  paLargeImage: "{mp} MP image. Containers accept up to 16 MP. Use a Native model.",
  paNoModels: "No automatic model",
  paNoModelsHint: "Start Poligome Runtime or a container.",
  paOpenHub: "Open AI models",
  paStopped: "stopped",
  paCapNative: "large images · region · settings",
  paCapContainer: "whole image",
  paNoImage: "Open an image first.",
  paBusy: "A pre-annotation is already running.",

  progressLabel: "Pre-annotating · {model}",
  progressImage: "image {i}/{n}",
  progressTiles: "part {done}/{total}",
  progressCancel: "Cancel",

  sumDone: "{count} created",
  sumDoneImages: "{count} created in {images} images",
  sumCanceled: "Canceled · {count} kept",
  sumFailed: "Failed on: {names}.",
  sumReview: "Review before exporting.",
  sumKeep: "Keep",
  sumUndo: "Undo",
  sumUndone: "Pre-annotation undone: {count} removed.",
  sumNone: "{model} found nothing.",
  sumReplaced: "{n} earlier ones replaced.",

  runRegion: "{model}: region {w}×{h}…",
  runWorking: "{model}: annotating…",
  runNoCoco: "{model}: response without COCO.",
  runHttp: "{model}: HTTP {status}",
  runRuntimeError: "Runtime: {detail}",
  runRuntimeUnreachable: "Poligome Runtime did not answer. See AI models › Connections.",
  runConnectorUnreachable: "Local connector did not answer. See AI models › Connections.",
};

const fr: AiCopy = {
  aiButton: "IA",
  aiHintSam: "Assisté : {model}",
  aiHintRuntime: "Natif : {model}",
  aiHintContainers: "Conteneurs actifs : {n}",
  aiHintNone: "Aucun modèle connecté. Cliquez pour configurer.",
  preAnnotate: "Pré-annoter",
  preAnnotateHint: "L’IA annote l’image ou le projet",

  hubTitle: "Modèles d’IA",
  hubSubtitle: "Assisté : vous pointez, l’IA découpe. Automatique : l’IA annote seule.",
  tabAssisted: "Assisté",
  tabAssistedHint: "Vous pointez, l’IA découpe",
  tabAutomatic: "Automatique",
  tabAutomaticHint: "L’IA annote seule",
  tabConnections: "Connexions",
  tabConnectionsHint: "Ce qui tourne",
  close: "Fermer",

  listStartHere: "Commencer ici",
  familySam2: "SAM 2.1 · recommandé",
  familyMedsam2: "Imagerie médicale",
  familySam3: "SAM 3 · concepts",
  inUse: "utilisé",
  installed: "installé",
  recommended: "Recommandé",
  experimental: "Expérimental",
  modelsList: "Modèles disponibles",

  howTitle: "Fonctionnement",
  howHint: "Où votre image est traitée",
  howIntro: "Tout tourne sur votre ordinateur. Aucune image ne part sur internet.",
  howFindsTitle: "La page ne trouve que les programmes déjà ouverts",
  howFindsBody: "Un navigateur ne peut pas lancer de programme. Laissez la fenêtre de l’installateur ouverte ; sous Linux, le service utilisateur s’en charge.",
  howModesTitle: "Assisté et Automatique sont indépendants",
  howModesBody: "Assisté découpe l’objet indiqué. Automatique annote toute l’image. L’un ne modifie pas le résultat de l’autre.",
  howPrivacyTitle: "Confidentialité",
  howPrivacyBody: "Images et prompts ne quittent pas l’ordinateur. Les conteneurs ne sont acceptés que sur 127.0.0.1 ou localhost.",

  autoGuideTitle: "Lequel choisir",
  autoGuideHint: "Natif ou Conteneur",
  autoNativeSection: "Natifs",
  autoNativeOffline: "Runtime arrêté",
  autoNativeOfflineHint: "Voir comment connecter",
  autoMineSection: "Mes modèles (Conteneur)",
  autoMineEmpty: "Aucun conteneur",
  autoAddModel: "Ajouter mon modèle",
  autoAddModelHint: "Docker : pas à pas",
  badgeNative: "Natif",
  badgeContainer: "Conteneur",
  stateUp: "actif",
  stateDown: "arrêté",

  guideIntro: "En Automatique, le modèle annote l’image seul. Il en existe deux types :",
  guideNativeTitle: "Natif",
  guideNativeBody: "Conçu pour Poligome. Gère les images énormes, montre le résultat en direct et propose des réglages.",
  guideContainerTitle: "Conteneur",
  guideContainerBody: "Votre modèle, dans Docker. Facile à brancher, mais il reçoit l’image entière et ne répond qu’à la fin.",
  guideColumnNeed: "Fonction",
  guideRowLarge: "Images énormes",
  guideRowRegion: "Une seule région",
  guideRowParams: "Réglages à l’écran",
  guideRowLive: "Résultat en direct",
  guideRowBatch: "Tout le projet",
  guideRowEffort: "Pour brancher",
  guideYes: "Oui",
  guideNo: "Non",
  guideLargeContainer: "Jusqu’à 16 MP",
  guideEffortNative: "Implémenter le protocole",
  guideEffortContainer: "Remplacer une fonction",
  guideRule: "Vous avez déjà un modèle ? Conteneur. Images énormes ou réglages sans code ? Natif.",
  guideReview: "Chaque pré-annotation s’annule en une fois.",

  nativeServedBy: "Tourne sur Poligome Runtime ({endpoint}).",
  nativeVersion: "Version",
  nativeLicense: "Licence",
  nativeProduces: "Produit",
  nativeAccepts: "Accepte",
  nativeLarge: "Grandes images",
  nativeLargeValue: "Par parties de {px} px max.",
  nativeLargeWhole: "Image entière",
  nativeParams: "Réglages",
  nativeNoParams: "Aucun",
  nativeNone: "—",
  geomBox: "boîtes",
  geomPolygon: "polygones",
  geomPolyline: "lignes",
  geomKeypoint: "points",
  geomMask: "masques",
  promptRegion: "région",
  promptPoints: "points",
  promptBox: "boîte",
  promptText: "texte",
  runtimeOfflineTitle: "Aucun modèle natif",
  runtimeOfflineBody: "Démarrez Poligome Runtime. Son modèle apparaîtra ici.",
  runtimeOfflineAddress: "Recherche sur {endpoint}. Autre adresse ? Modifiez-la dans Connexions.",
  openConnections: "Ouvrir Connexions",
  usePreannotate: "Pré-annoter avec ce modèle",

  containerUp: "actif",
  containerDown: "arrêté",
  containerImage: "image {name}",
  containerLimits: "Limites",
  containerClasses: "Classes",
  containerParams: "Paramètres",
  containerEnv: "Environnement",
  containerLastRun: "Dernière exécution",
  annotationOne: "{n} annotation",
  annotationMany: "{n} annotations",
  fieldName: "Nom",
  fieldPort: "Port",
  fieldNote: "Note",
  fieldNotePlaceholder: "À quoi il sert, quoi vérifier.",
  cancel: "Annuler",
  save: "Enregistrer",
  saveFailed: "Impossible d’enregistrer : {detail}",
  editContainer: "Modifier",
  removeContainer: "Retirer de la liste (le conteneur reste dans Docker)",
  containerStoppedHint: "Conteneur arrêté. Démarrez-le avec la commande start de la CLI.",
  byomNoMetadataReady: "Pas de description. Lancez-le une fois pour voir ce qu’il produit.",
  byomNoMetadataDown: "Pas de description. Démarrez le conteneur pour voir ses classes.",
  byomDeclares: "{n} classes : {list}.",
  byomDeclaresOne: "1 classe : {list}.",
  byomObserved: "Dernière exécution : {n} classes ({list}).",
  byomObservedOne: "Dernière exécution : 1 classe ({list}).",
  byomExports: "Produit {list}.",
  byomLastImage: "Dernière image : {count}.",
  listAnd: "et",

  connIntro: "Programmes de votre ordinateur utilisés par l’IA.",
  connConnectorTitle: "Connecteur local",
  connConnectorRole: "Pour Assisté (SAM) et les Conteneurs.",
  connRuntimeTitle: "Poligome Runtime",
  connRuntimeRole: "Pour les modèles Natifs.",
  connContainersTitle: "Conteneurs",
  connContainersRole: "Vos modèles dans Docker.",
  connUp: "Connecté",
  connDown: "Arrêté",
  connChecking: "Vérification…",
  connServing: "Exécute {model}",
  connHost: "sur {host}",
  connAddress: "Adresse",
  connRetry: "Vérifier",
  connContainersCount: "{up} sur {total} actifs",
  connContainersNone: "Aucun conteneur.",
  connContainersNeedConnector: "Nécessite le connecteur en marche.",
  connConnectorHow: "Installez-le depuis l’onglet Assisté.",
  connConnectorHowButton: "Installer",
  connContainersHowButton: "Ajouter",
  connPortClash: "Le port 7861 est aussi celui du convertisseur COG. Si les deux tournent, changez l’un des ports.",

  paSubtitle: "L’IA annote. Vous relisez ou annulez.",
  paModel: "Modèle",
  paWhere: "Où",
  paParams: "Réglages",
  paScopeImage: "Cette image",
  paScopeRegion: "Région sélectionnée",
  paScopeAll: "Toutes ({n})",
  paRegionNeedsBox: "Sélectionnez une boîte comme région.",
  paRegionNativeOnly: "Région : modèles Natifs uniquement.",
  paLargeImage: "Image de {mp} MP. Les conteneurs acceptent 16 MP max. Utilisez un modèle Natif.",
  paNoModels: "Aucun modèle automatique",
  paNoModelsHint: "Démarrez Poligome Runtime ou un conteneur.",
  paOpenHub: "Ouvrir les modèles d’IA",
  paStopped: "arrêté",
  paCapNative: "grandes images · région · réglages",
  paCapContainer: "image entière",
  paNoImage: "Ouvrez d’abord une image.",
  paBusy: "Une pré-annotation est déjà en cours.",

  progressLabel: "Pré-annotation · {model}",
  progressImage: "image {i}/{n}",
  progressTiles: "partie {done}/{total}",
  progressCancel: "Annuler",

  sumDone: "{count} créées",
  sumDoneImages: "{count} créées dans {images} images",
  sumCanceled: "Annulé · {count} conservées",
  sumFailed: "Échec sur : {names}.",
  sumReview: "Relisez avant d’exporter.",
  sumKeep: "Garder",
  sumUndo: "Annuler",
  sumUndone: "Pré-annotation annulée : {count} supprimées.",
  sumNone: "{model} n’a rien trouvé.",
  sumReplaced: "{n} précédentes remplacées.",

  runRegion: "{model} : région {w}×{h}…",
  runWorking: "{model} : annotation…",
  runNoCoco: "{model} : réponse sans COCO.",
  runHttp: "{model} : HTTP {status}",
  runRuntimeError: "Runtime : {detail}",
  runRuntimeUnreachable: "Poligome Runtime ne répond pas. Voir Modèles d’IA › Connexions.",
  runConnectorUnreachable: "Le connecteur local ne répond pas. Voir Modèles d’IA › Connexions.",
};

const es: AiCopy = {
  aiButton: "IA",
  aiHintSam: "Asistido: {model}",
  aiHintRuntime: "Nativo: {model}",
  aiHintContainers: "Contenedores activos: {n}",
  aiHintNone: "Ningún modelo conectado. Haz clic para configurar.",
  preAnnotate: "Pre-anotar",
  preAnnotateHint: "La IA anota la imagen o el proyecto",

  hubTitle: "Modelos de IA",
  hubSubtitle: "Asistido: tú señalas, la IA recorta. Automático: la IA anota sola.",
  tabAssisted: "Asistido",
  tabAssistedHint: "Tú señalas, la IA recorta",
  tabAutomatic: "Automático",
  tabAutomaticHint: "La IA anota sola",
  tabConnections: "Conexiones",
  tabConnectionsHint: "Lo que está corriendo",
  close: "Cerrar",

  listStartHere: "Empieza aquí",
  familySam2: "SAM 2.1 · recomendado",
  familyMedsam2: "Imagen médica",
  familySam3: "SAM 3 · conceptos",
  inUse: "en uso",
  installed: "instalado",
  recommended: "Recomendado",
  experimental: "Experimental",
  modelsList: "Modelos disponibles",

  howTitle: "Cómo funciona",
  howHint: "Dónde se procesa tu imagen",
  howIntro: "Todo corre en tu ordenador. Ninguna imagen sale a internet.",
  howFindsTitle: "La página solo encuentra programas ya abiertos",
  howFindsBody: "El navegador no puede iniciar programas. Deja abierta la ventana del instalador; en Linux, el servicio de usuario lo hace por ti.",
  howModesTitle: "Asistido y Automático son independientes",
  howModesBody: "Asistido recorta el objeto que señalas. Automático anota la imagen entera. Uno no cambia el resultado del otro.",
  howPrivacyTitle: "Privacidad",
  howPrivacyBody: "Imágenes y prompts no salen del ordenador. Los contenedores solo se aceptan en 127.0.0.1 o localhost.",

  autoGuideTitle: "Cuál elegir",
  autoGuideHint: "Nativo o Contenedor",
  autoNativeSection: "Nativos",
  autoNativeOffline: "Runtime apagado",
  autoNativeOfflineHint: "Ver cómo conectar",
  autoMineSection: "Mis modelos (Contenedor)",
  autoMineEmpty: "Ningún contenedor",
  autoAddModel: "Añadir mi modelo",
  autoAddModelHint: "Docker: paso a paso",
  badgeNative: "Nativo",
  badgeContainer: "Contenedor",
  stateUp: "activo",
  stateDown: "detenido",

  guideIntro: "En Automático, el modelo anota la imagen solo. Hay dos tipos:",
  guideNativeTitle: "Nativo",
  guideNativeBody: "Hecho para Poligome. Aguanta imágenes enormes, muestra el resultado mientras corre y tiene ajustes en pantalla.",
  guideContainerTitle: "Contenedor",
  guideContainerBody: "Tu propio modelo, en Docker. Fácil de conectar, pero recibe la imagen entera y solo responde al final.",
  guideColumnNeed: "Función",
  guideRowLarge: "Imágenes enormes",
  guideRowRegion: "Solo una región",
  guideRowParams: "Ajustes en pantalla",
  guideRowLive: "Resultado en vivo",
  guideRowBatch: "Todo el proyecto",
  guideRowEffort: "Para conectar",
  guideYes: "Sí",
  guideNo: "No",
  guideLargeContainer: "Hasta 16 MP",
  guideEffortNative: "Implementar el protocolo",
  guideEffortContainer: "Cambiar una función",
  guideRule: "¿Ya tienes un modelo? Contenedor. ¿Imágenes enormes o ajustes sin código? Nativo.",
  guideReview: "Cada pre-anotación se deshace de una vez.",

  nativeServedBy: "Corriendo en Poligome Runtime ({endpoint}).",
  nativeVersion: "Versión",
  nativeLicense: "Licencia",
  nativeProduces: "Produce",
  nativeAccepts: "Acepta",
  nativeLarge: "Imágenes grandes",
  nativeLargeValue: "En partes de hasta {px} px",
  nativeLargeWhole: "Imagen entera",
  nativeParams: "Ajustes",
  nativeNoParams: "Ninguno",
  nativeNone: "—",
  geomBox: "cajas",
  geomPolygon: "polígonos",
  geomPolyline: "líneas",
  geomKeypoint: "puntos",
  geomMask: "máscaras",
  promptRegion: "región",
  promptPoints: "puntos",
  promptBox: "caja",
  promptText: "texto",
  runtimeOfflineTitle: "Ningún modelo nativo",
  runtimeOfflineBody: "Inicia Poligome Runtime. Su modelo aparece aquí.",
  runtimeOfflineAddress: "Buscando en {endpoint}. ¿Otra dirección? Cámbiala en Conexiones.",
  openConnections: "Abrir Conexiones",
  usePreannotate: "Pre-anotar con este modelo",

  containerUp: "activo",
  containerDown: "detenido",
  containerImage: "imagen {name}",
  containerLimits: "Limitaciones",
  containerClasses: "Clases",
  containerParams: "Parámetros",
  containerEnv: "Entorno",
  containerLastRun: "Última ejecución",
  annotationOne: "{n} anotación",
  annotationMany: "{n} anotaciones",
  fieldName: "Nombre",
  fieldPort: "Puerto",
  fieldNote: "Nota",
  fieldNotePlaceholder: "Para qué sirve, qué revisar.",
  cancel: "Cancelar",
  save: "Guardar",
  saveFailed: "No se pudo guardar: {detail}",
  editContainer: "Editar",
  removeContainer: "Quitar de la lista (el contenedor sigue en Docker)",
  containerStoppedHint: "Contenedor detenido. Inícialo con el comando start de la CLI.",
  byomNoMetadataReady: "Sin descripción. Ejecútalo una vez para ver qué produce.",
  byomNoMetadataDown: "Sin descripción. Inicia el contenedor para ver sus clases.",
  byomDeclares: "{n} clases: {list}.",
  byomDeclaresOne: "1 clase: {list}.",
  byomObserved: "Última ejecución: {n} clases ({list}).",
  byomObservedOne: "Última ejecución: 1 clase ({list}).",
  byomExports: "Produce {list}.",
  byomLastImage: "Última imagen: {count}.",
  listAnd: "y",

  connIntro: "Programas de tu ordenador que usa la IA.",
  connConnectorTitle: "Conector local",
  connConnectorRole: "Para Asistido (SAM) y los Contenedores.",
  connRuntimeTitle: "Poligome Runtime",
  connRuntimeRole: "Para los modelos Nativos.",
  connContainersTitle: "Contenedores",
  connContainersRole: "Tus modelos en Docker.",
  connUp: "Conectado",
  connDown: "Apagado",
  connChecking: "Comprobando…",
  connServing: "Corriendo {model}",
  connHost: "en {host}",
  connAddress: "Dirección",
  connRetry: "Comprobar",
  connContainersCount: "{up} de {total} activos",
  connContainersNone: "Ningún contenedor.",
  connContainersNeedConnector: "Necesita el conector encendido.",
  connConnectorHow: "Instálalo desde la pestaña Asistido.",
  connConnectorHowButton: "Instalar",
  connContainersHowButton: "Añadir",
  connPortClash: "El puerto 7861 también es del conversor de COG. Si corren los dos, cambia uno de los puertos.",

  paSubtitle: "La IA anota. Tú revisas o deshaces.",
  paModel: "Modelo",
  paWhere: "Dónde",
  paParams: "Ajustes",
  paScopeImage: "Esta imagen",
  paScopeRegion: "Región seleccionada",
  paScopeAll: "Todas ({n})",
  paRegionNeedsBox: "Selecciona una caja para usarla como región.",
  paRegionNativeOnly: "Región: solo modelos Nativos.",
  paLargeImage: "Imagen de {mp} MP. Los contenedores aceptan hasta 16 MP. Usa un modelo Nativo.",
  paNoModels: "Ningún modelo automático",
  paNoModelsHint: "Inicia Poligome Runtime o un contenedor.",
  paOpenHub: "Abrir modelos de IA",
  paStopped: "detenido",
  paCapNative: "imágenes grandes · región · ajustes",
  paCapContainer: "imagen entera",
  paNoImage: "Abre una imagen primero.",
  paBusy: "Ya hay una pre-anotación en curso.",

  progressLabel: "Pre-anotando · {model}",
  progressImage: "imagen {i}/{n}",
  progressTiles: "parte {done}/{total}",
  progressCancel: "Cancelar",

  sumDone: "{count} creadas",
  sumDoneImages: "{count} creadas en {images} imágenes",
  sumCanceled: "Cancelado · {count} conservadas",
  sumFailed: "Falló en: {names}.",
  sumReview: "Revisa antes de exportar.",
  sumKeep: "Mantener",
  sumUndo: "Deshacer",
  sumUndone: "Pre-anotación deshecha: {count} eliminadas.",
  sumNone: "{model} no encontró nada.",
  sumReplaced: "{n} anteriores reemplazadas.",

  runRegion: "{model}: región {w}×{h}…",
  runWorking: "{model}: anotando…",
  runNoCoco: "{model}: respuesta sin COCO.",
  runHttp: "{model}: HTTP {status}",
  runRuntimeError: "Runtime: {detail}",
  runRuntimeUnreachable: "Poligome Runtime no respondió. Mira en Modelos de IA › Conexiones.",
  runConnectorUnreachable: "El conector local no respondió. Mira en Modelos de IA › Conexiones.",
};

const translations: Record<Language, AiCopy> = { pt, en, fr, es };

export function getAiCopy(language: Language): AiCopy {
  return translations[language];
}

/** "{n} anotação" ou "{n} anotações", já preenchido. */
export function countAnnotations(copy: AiCopy, n: number): string {
  return (n === 1 ? copy.annotationOne : copy.annotationMany).replace("{n}", String(n));
}

/** "a, b e c" no idioma pedido. */
export function joinList(copy: AiCopy, items: readonly string[]): string {
  if (items.length <= 1) return items.join("");
  return `${items.slice(0, -1).join(", ")} ${copy.listAnd} ${items[items.length - 1]}`;
}
