import type { Language } from "./i18n";

/**
 * Os textos da área de IA: o botão do topo, a central de modelos, o diálogo de
 * pré-anotação e o resumo de cada execução.
 *
 * Ficam fora de `i18n.ts` porque formam um vocabulário próprio — Assistido e
 * Automático, Nativo e Contêiner — que precisa ser dito do mesmo jeito em todas
 * as telas. Juntos aqui, uma troca de palavra muda tudo de uma vez.
 *
 * A tipagem é a mesma do resto: cada idioma precisa ter todas as chaves do
 * português, e o compilador recusa o que faltar.
 */
const pt = {
  aiButton: "IA",
  aiHintSam: "Assistido: {model}",
  aiHintRuntime: "Nativo: {model}",
  aiHintContainers: "Contêineres no ar: {n}",
  aiHintNone: "Nenhum modelo de IA conectado. Clique para configurar.",
  preAnnotate: "Pré-anotar",
  preAnnotateHint: "A IA anota sozinha a imagem, uma região ou o projeto inteiro",

  hubTitle: "Modelos de IA",
  hubSubtitle: "Assistido: você aponta e a IA recorta. Automático: a IA anota sozinha e você revisa.",
  tabAssisted: "Assistido",
  tabAssistedHint: "Você aponta, a IA recorta",
  tabAutomatic: "Automático",
  tabAutomaticHint: "A IA anota sozinha",
  tabConnections: "Conexões",
  tabConnectionsHint: "O que roda na sua máquina",
  close: "Fechar",

  listStartHere: "Comece por aqui",
  familySam2: "SAM 2.1 · recomendado",
  familyMedsam2: "Domínio · imagem médica",
  familySam3: "SAM 3 · conceitos",
  inUse: "em uso",
  installed: "instalado",
  recommended: "Recomendado",
  experimental: "Experimental",
  modelsList: "Modelos disponíveis",

  howTitle: "Como funciona",
  howHint: "O conector, os modelos e a sua imagem num desenho",
  howIntro: "O Poligome não manda imagem para servidor nenhum. Quem carrega o modelo e roda a inferência é um programa na sua máquina, e a página só conversa com ele.",
  howFindsTitle: "A página encontra, nunca liga",
  howFindsBody: "Ao abrir o editor e a cada volta à aba, a página procura os programas locais e adota o que já estiver carregado. Nenhuma página web pode iniciar um processo ou subir um contêiner — é regra do navegador. Por isso a janela do instalador precisa ficar aberta, ou, no Linux, o serviço de usuário faz esse papel.",
  howModesTitle: "Assistido e Automático convivem",
  howModesBody: "No Assistido você aponta o objeto — clicando, arrastando uma caixa ou, no SAM 3, escrevendo — e a IA recorta só ele. No Automático o modelo recebe a imagem e devolve tudo o que encontrou. Os dois podem estar prontos ao mesmo tempo, e um não altera o resultado do outro.",
  howPrivacyTitle: "Inferência local",
  howPrivacyBody: "Imagens e prompts ficam no computador. Contêineres só são aceitos em 127.0.0.1 ou localhost: um endereço remoto tiraria as imagens da sua máquina, que é justamente o que o Poligome evita.",

  autoGuideTitle: "Como escolher",
  autoGuideHint: "Nativo ou Contêiner, lado a lado",
  autoNativeSection: "Nativos · Poligome Runtime",
  autoNativeOffline: "Runtime não encontrado",
  autoNativeOfflineHint: "Ver como conectar",
  autoMineSection: "Meus modelos · Contêiner",
  autoMineEmpty: "Nenhum contêiner registrado",
  autoAddModel: "Adicionar meu modelo",
  autoAddModelHint: "Docker · contrato e passo a passo",
  badgeNative: "Nativo",
  badgeContainer: "Contêiner",
  stateUp: "no ar",
  stateDown: "parado",

  guideIntro: "No Automático você não aponta nada: o modelo recebe a imagem e devolve as anotações prontas, com as classes dele. Há dois tipos de modelo, e a diferença está em quanto trabalho dá plugá-lo e no que você ganha em troca.",
  guideNativeTitle: "Nativo — feito para o Poligome",
  guideNativeBody: "Roda no Poligome Runtime, que divide a imagem em partes. Por isso aguenta ortofotos e GeoTIFFs enormes, desenha o resultado enquanto avança, aceita só a região que você selecionou e oferece ajustes na tela.",
  guideContainerTitle: "Contêiner — o modelo que você já tem",
  guideContainerBody: "Qualquer modelo num contêiner Docker com o contrato do SageMaker. Plugar é quase imediato e o mesmo contêiner serve em outros lugares, mas ele recebe a imagem inteira de uma vez e o resultado só aparece no fim.",
  guideColumnNeed: "O que você precisa",
  guideRowLarge: "Imagens muito grandes",
  guideRowRegion: "Só a região selecionada",
  guideRowParams: "Ajustes na tela",
  guideRowLive: "Resultado enquanto roda",
  guideRowBatch: "Todas as imagens do projeto",
  guideRowEffort: "Esforço para plugar",
  guideYes: "Sim",
  guideNo: "Não",
  guideLargeContainer: "Até 16 MP",
  guideEffortNative: "Implementar o protocolo do runtime",
  guideEffortContainer: "Trocar uma função no exemplo",
  guideRule: "Regra prática: já tem um modelo e fotos de tamanho comum? Contêiner. Trabalha com imagens enormes, ou quer ajustar e rodar de novo sem mexer em código? Nativo.",
  guideReview: "Nos dois casos o resultado entra no projeto como qualquer anotação, e o fim de cada execução oferece desfazer tudo de uma vez.",

  nativeServedBy: "Servido pelo Poligome Runtime em {endpoint}.",
  nativeVersion: "Versão",
  nativeLicense: "Licença",
  nativeProduces: "Produz",
  nativeAccepts: "Aceita",
  nativeLarge: "Imagens grandes",
  nativeLargeValue: "Divide em partes de até {px} px",
  nativeLargeWhole: "Recebe a imagem inteira",
  nativeParams: "Ajustes",
  nativeNoParams: "Este modelo não declara ajustes.",
  nativeNone: "—",
  geomBox: "caixas",
  geomPolygon: "polígonos",
  geomPolyline: "linhas",
  geomKeypoint: "pontos",
  geomMask: "máscaras",
  promptRegion: "região",
  promptPoints: "pontos",
  promptBox: "caixa",
  promptText: "texto",
  runtimeOfflineTitle: "Nenhum modelo nativo conectado",
  runtimeOfflineBody: "Modelos nativos rodam no Poligome Runtime, um programa separado do conector do SAM. Quando ele estiver rodando nesta máquina, o modelo que ele serve aparece aqui sozinho.",
  runtimeOfflineAddress: "A página procura em {endpoint}. Se o seu runtime usa outra porta, ajuste em Conexões.",
  openConnections: "Abrir Conexões",
  usePreannotate: "Pré-anotar com este modelo",

  containerUp: "contêiner no ar",
  containerDown: "contêiner parado",
  containerImage: "imagem {name}",
  containerLimits: "Limitações declaradas pelo modelo",
  containerClasses: "Classes exportadas",
  containerParams: "Parâmetros do modelo",
  containerEnv: "Ambiente do contêiner",
  containerLastRun: "Última execução",
  annotationOne: "{n} anotação",
  annotationMany: "{n} anotações",
  fieldName: "Nome",
  fieldPort: "Porta",
  fieldNote: "Anotação",
  fieldNotePlaceholder: "Para que serve, em que dados foi treinado, o que revisar com atenção.",
  cancel: "Cancelar",
  save: "Salvar",
  saveFailed: "Não foi possível salvar: {detail}",
  editContainer: "Editar nome, porta e anotação",
  removeContainer: "Remover o registro; a imagem e o contêiner continuam no Docker",
  containerStoppedHint: "O contêiner está parado. Suba-o com o comando start da CLI do BYOM e volte a esta tela.",
  byomNoMetadataReady: "Este contêiner não implementa GET /metadata e ainda não foi executado, então não há o que descrever. Rode-o uma vez sobre uma imagem.",
  byomNoMetadataDown: "O contêiner está parado, então não dá para descrevê-lo. Suba-o para ver as classes que ele exporta.",
  byomDeclares: "Declara {n} classes: {list}.",
  byomDeclaresOne: "Declara 1 classe: {list}.",
  byomObserved: "Na última execução devolveu {n} classes: {list}.",
  byomObservedOne: "Na última execução devolveu 1 classe: {list}.",
  byomExports: "Exporta {list}.",
  byomLastImage: "Na última imagem produziu {count}.",
  listAnd: "e",

  connIntro: "Tudo o que a IA usa roda na sua máquina. A página só encontra esses programas; ligar e desligar fica com você.",
  connConnectorTitle: "Conector local",
  connConnectorRole: "Atende o modo Assistido (SAM) e repassa aos modelos Contêiner.",
  connRuntimeTitle: "Poligome Runtime",
  connRuntimeRole: "Atende os modelos Nativos do modo Automático.",
  connContainersTitle: "Contêineres",
  connContainersRole: "Seus modelos em Docker, alcançados através do conector.",
  connUp: "Conectado",
  connDown: "Não encontrado",
  connChecking: "Verificando…",
  connServing: "Servindo {model}",
  connHost: "Atendendo de {host}",
  connAddress: "Endereço",
  connRetry: "Verificar de novo",
  connContainersCount: "{up} de {total} no ar",
  connContainersNone: "Nenhum contêiner registrado.",
  connContainersNeedConnector: "Sem o conector, os contêineres não são alcançados.",
  connConnectorHow: "Para instalar ou iniciar, escolha um modelo no modo Assistido: o passo a passo está na ficha dele.",
  connConnectorHowButton: "Ver instalação",
  connContainersHowButton: "Ver como adicionar",
  connPortClash: "A porta 7861 também é a padrão do conversor de COG. Se os dois estiverem rodando, só um atende: mude a porta de um deles e o endereço aqui.",

  paSubtitle: "A IA anota sozinha. Você revisa e, se não gostar, desfaz tudo de uma vez.",
  paModel: "Modelo",
  paWhere: "Onde",
  paParams: "Ajustes",
  paScopeImage: "Esta imagem",
  paScopeRegion: "Região selecionada",
  paScopeAll: "Todas as imagens ({n})",
  paRegionNeedsBox: "Selecione uma caixa na imagem para usá-la como região.",
  paRegionNativeOnly: "Só modelos Nativos recebem uma região; um Contêiner sempre recebe a imagem inteira.",
  paLargeImage: "Esta imagem tem {mp} MP. Um modelo Contêiner recebe a imagem inteira, e o conector recusa acima de 16 MP. Prefira um modelo Nativo.",
  paNoModels: "Nenhum modelo automático disponível",
  paNoModelsHint: "Inicie o Poligome Runtime, suba um contêiner ou adicione o seu modelo.",
  paOpenHub: "Abrir modelos de IA",
  paStopped: "parado — suba o contêiner para usar",
  paCapNative: "imagens grandes · região · ajustes · progresso",
  paCapContainer: "imagem inteira · resultado no fim",
  paNoImage: "Abra uma imagem antes de pré-anotar.",
  paBusy: "Já há uma pré-anotação em andamento.",

  progressLabel: "Pré-anotando com {model}",
  progressImage: "imagem {i} de {n}",
  progressTiles: "parte {done} de {total}",
  progressCancel: "Cancelar",

  sumDone: "Pré-anotação concluída: {count}",
  sumDoneImages: "Pré-anotação concluída: {count} em {images} imagens",
  sumCanceled: "Pré-anotação cancelada: {count} já tinham chegado",
  sumFailed: "Falhou em {names}.",
  sumReview: "As anotações já estão no projeto. Revise antes de exportar.",
  sumKeep: "Manter",
  sumUndo: "Desfazer pré-anotação",
  sumUndone: "Pré-anotação desfeita: {count} removidas.",
  sumNone: "{model} não devolveu nenhuma anotação.",
  sumReplaced: "{n} anteriores do mesmo modelo foram substituídas.",

  runRegion: "{model}: região {w}×{h}…",
  runWorking: "{model}: anotando…",
  runNoCoco: "{model}: o contêiner respondeu sem documento COCO.",
  runHttp: "{model}: HTTP {status}",
  runRuntimeError: "Poligome Runtime: {detail}",
  runRuntimeUnreachable: "O Poligome Runtime não respondeu. Ele é um programa separado do conector do SAM: confira em Modelos de IA › Conexões se ele está rodando no endereço configurado.",
  runConnectorUnreachable: "O conector local não respondeu, e é por ele que os modelos Contêiner são alcançados. Confira em Modelos de IA › Conexões.",
};

export type AiCopyKey = keyof typeof pt;
export type AiCopy = Record<AiCopyKey, string>;

const en: AiCopy = {
  aiButton: "AI",
  aiHintSam: "Assisted: {model}",
  aiHintRuntime: "Native: {model}",
  aiHintContainers: "Containers up: {n}",
  aiHintNone: "No AI model connected. Click to set one up.",
  preAnnotate: "Pre-annotate",
  preAnnotateHint: "The AI annotates the image, a region or the whole project on its own",

  hubTitle: "AI models",
  hubSubtitle: "Assisted: you point and the AI cuts it out. Automatic: the AI annotates on its own and you review.",
  tabAssisted: "Assisted",
  tabAssistedHint: "You point, the AI cuts out",
  tabAutomatic: "Automatic",
  tabAutomaticHint: "The AI annotates on its own",
  tabConnections: "Connections",
  tabConnectionsHint: "What runs on your machine",
  close: "Close",

  listStartHere: "Start here",
  familySam2: "SAM 2.1 · recommended",
  familyMedsam2: "Domain · medical imaging",
  familySam3: "SAM 3 · concepts",
  inUse: "in use",
  installed: "installed",
  recommended: "Recommended",
  experimental: "Experimental",
  modelsList: "Available models",

  howTitle: "How it works",
  howHint: "The connector, the models and your image in one drawing",
  howIntro: "Poligome sends images to no server. The model is loaded and run by a program on your own machine, and the page only talks to it.",
  howFindsTitle: "The page finds, it never starts",
  howFindsBody: "When the editor opens, and every time you return to the tab, the page looks for the local programs and adopts whatever is already loaded. No web page can start a process or a container — that is a browser rule. That is why the installer window has to stay open, or, on Linux, why the user service takes its place.",
  howModesTitle: "Assisted and Automatic work side by side",
  howModesBody: "In Assisted you point at the object — by clicking, dragging a box or, with SAM 3, typing — and the AI cuts out just that. In Automatic the model receives the image and returns everything it found. Both can be ready at once, and neither changes the other's result.",
  howPrivacyTitle: "Local inference",
  howPrivacyBody: "Images and prompts stay on the computer. Containers are only accepted on 127.0.0.1 or localhost: a remote address would take the images off your machine, which is exactly what Poligome avoids.",

  autoGuideTitle: "How to choose",
  autoGuideHint: "Native or Container, side by side",
  autoNativeSection: "Native · Poligome Runtime",
  autoNativeOffline: "Runtime not found",
  autoNativeOfflineHint: "See how to connect",
  autoMineSection: "My models · Container",
  autoMineEmpty: "No container registered",
  autoAddModel: "Add my model",
  autoAddModelHint: "Docker · contract and walkthrough",
  badgeNative: "Native",
  badgeContainer: "Container",
  stateUp: "up",
  stateDown: "stopped",

  guideIntro: "In Automatic you point at nothing: the model receives the image and returns finished annotations, with its own classes. There are two kinds of model, and they differ in how much work it takes to plug one in and what you get in return.",
  guideNativeTitle: "Native — built for Poligome",
  guideNativeBody: "Runs on Poligome Runtime, which splits the image into parts. That is why it copes with huge orthophotos and GeoTIFFs, draws results as it goes, accepts just the region you selected and offers on-screen settings.",
  guideContainerTitle: "Container — the model you already have",
  guideContainerBody: "Any model in a Docker container with the SageMaker contract. Plugging it in is almost immediate and the same container works elsewhere, but it receives the whole image at once and results only appear at the end.",
  guideColumnNeed: "What you need",
  guideRowLarge: "Very large images",
  guideRowRegion: "Just the selected region",
  guideRowParams: "On-screen settings",
  guideRowLive: "Results while it runs",
  guideRowBatch: "Every image in the project",
  guideRowEffort: "Effort to plug in",
  guideYes: "Yes",
  guideNo: "No",
  guideLargeContainer: "Up to 16 MP",
  guideEffortNative: "Implement the runtime protocol",
  guideEffortContainer: "Replace one function in the example",
  guideRule: "Rule of thumb: already have a model and ordinary-sized photos? Container. Working with huge images, or want to tweak and rerun without touching code? Native.",
  guideReview: "Either way the result enters the project like any other annotation, and the end of each run offers to undo all of it at once.",

  nativeServedBy: "Served by Poligome Runtime at {endpoint}.",
  nativeVersion: "Version",
  nativeLicense: "License",
  nativeProduces: "Produces",
  nativeAccepts: "Accepts",
  nativeLarge: "Large images",
  nativeLargeValue: "Splits into parts up to {px} px",
  nativeLargeWhole: "Receives the whole image",
  nativeParams: "Settings",
  nativeNoParams: "This model declares no settings.",
  nativeNone: "—",
  geomBox: "boxes",
  geomPolygon: "polygons",
  geomPolyline: "lines",
  geomKeypoint: "points",
  geomMask: "masks",
  promptRegion: "region",
  promptPoints: "points",
  promptBox: "box",
  promptText: "text",
  runtimeOfflineTitle: "No native model connected",
  runtimeOfflineBody: "Native models run on Poligome Runtime, a program separate from the SAM connector. Once it is running on this machine, the model it serves shows up here on its own.",
  runtimeOfflineAddress: "The page looks at {endpoint}. If your runtime uses another port, change it in Connections.",
  openConnections: "Open Connections",
  usePreannotate: "Pre-annotate with this model",

  containerUp: "container up",
  containerDown: "container stopped",
  containerImage: "image {name}",
  containerLimits: "Limitations declared by the model",
  containerClasses: "Exported classes",
  containerParams: "Model parameters",
  containerEnv: "Container environment",
  containerLastRun: "Last run",
  annotationOne: "{n} annotation",
  annotationMany: "{n} annotations",
  fieldName: "Name",
  fieldPort: "Port",
  fieldNote: "Note",
  fieldNotePlaceholder: "What it is for, what data it was trained on, what to review carefully.",
  cancel: "Cancel",
  save: "Save",
  saveFailed: "Could not save: {detail}",
  editContainer: "Edit name, port and note",
  removeContainer: "Remove the registration; the image and the container stay in Docker",
  containerStoppedHint: "The container is stopped. Start it with the BYOM CLI start command and come back to this screen.",
  byomNoMetadataReady: "This container does not implement GET /metadata and has not run yet, so there is nothing to describe. Run it once on an image.",
  byomNoMetadataDown: "The container is stopped, so it cannot be described. Start it to see the classes it exports.",
  byomDeclares: "Declares {n} classes: {list}.",
  byomDeclaresOne: "Declares 1 class: {list}.",
  byomObserved: "Returned {n} classes on its last run: {list}.",
  byomObservedOne: "Returned 1 class on its last run: {list}.",
  byomExports: "Exports {list}.",
  byomLastImage: "Produced {count} on the last image.",
  listAnd: "and",

  connIntro: "Everything the AI uses runs on your machine. The page only finds these programs; starting and stopping them is up to you.",
  connConnectorTitle: "Local connector",
  connConnectorRole: "Serves Assisted mode (SAM) and forwards to Container models.",
  connRuntimeTitle: "Poligome Runtime",
  connRuntimeRole: "Serves the Native models of Automatic mode.",
  connContainersTitle: "Containers",
  connContainersRole: "Your models in Docker, reached through the connector.",
  connUp: "Connected",
  connDown: "Not found",
  connChecking: "Checking…",
  connServing: "Serving {model}",
  connHost: "Answering from {host}",
  connAddress: "Address",
  connRetry: "Check again",
  connContainersCount: "{up} of {total} up",
  connContainersNone: "No container registered.",
  connContainersNeedConnector: "Without the connector, containers cannot be reached.",
  connConnectorHow: "To install or start it, pick a model in Assisted mode: the walkthrough is on its card.",
  connConnectorHowButton: "See installation",
  connContainersHowButton: "See how to add one",
  connPortClash: "Port 7861 is also the COG converter's default. If both are running only one answers: change the port of one of them, and the address here.",

  paSubtitle: "The AI annotates on its own. You review it and, if you don't like it, undo it all at once.",
  paModel: "Model",
  paWhere: "Where",
  paParams: "Settings",
  paScopeImage: "This image",
  paScopeRegion: "Selected region",
  paScopeAll: "Every image ({n})",
  paRegionNeedsBox: "Select a box on the image to use it as the region.",
  paRegionNativeOnly: "Only Native models accept a region; a Container always receives the whole image.",
  paLargeImage: "This image is {mp} MP. A Container model receives the whole image, and the connector refuses anything above 16 MP. Prefer a Native model.",
  paNoModels: "No automatic model available",
  paNoModelsHint: "Start Poligome Runtime, bring up a container or add your own model.",
  paOpenHub: "Open AI models",
  paStopped: "stopped — start the container to use it",
  paCapNative: "large images · region · settings · progress",
  paCapContainer: "whole image · results at the end",
  paNoImage: "Open an image before pre-annotating.",
  paBusy: "A pre-annotation is already running.",

  progressLabel: "Pre-annotating with {model}",
  progressImage: "image {i} of {n}",
  progressTiles: "part {done} of {total}",
  progressCancel: "Cancel",

  sumDone: "Pre-annotation finished: {count}",
  sumDoneImages: "Pre-annotation finished: {count} across {images} images",
  sumCanceled: "Pre-annotation canceled: {count} had already arrived",
  sumFailed: "Failed on {names}.",
  sumReview: "The annotations are already in the project. Review them before exporting.",
  sumKeep: "Keep",
  sumUndo: "Undo pre-annotation",
  sumUndone: "Pre-annotation undone: {count} removed.",
  sumNone: "{model} returned no annotations.",
  sumReplaced: "{n} earlier ones from the same model were replaced.",

  runRegion: "{model}: region {w}×{h}…",
  runWorking: "{model}: annotating…",
  runNoCoco: "{model}: the container answered without a COCO document.",
  runHttp: "{model}: HTTP {status}",
  runRuntimeError: "Poligome Runtime: {detail}",
  runRuntimeUnreachable: "Poligome Runtime did not answer. It is a program separate from the SAM connector: check in AI models › Connections that it is running at the configured address.",
  runConnectorUnreachable: "The local connector did not answer, and Container models are reached through it. Check in AI models › Connections.",
};

const fr: AiCopy = {
  aiButton: "IA",
  aiHintSam: "Assisté : {model}",
  aiHintRuntime: "Natif : {model}",
  aiHintContainers: "Conteneurs actifs : {n}",
  aiHintNone: "Aucun modèle d’IA connecté. Cliquez pour en configurer un.",
  preAnnotate: "Pré-annoter",
  preAnnotateHint: "L’IA annote seule l’image, une région ou tout le projet",

  hubTitle: "Modèles d’IA",
  hubSubtitle: "Assisté : vous pointez et l’IA découpe. Automatique : l’IA annote seule et vous relisez.",
  tabAssisted: "Assisté",
  tabAssistedHint: "Vous pointez, l’IA découpe",
  tabAutomatic: "Automatique",
  tabAutomaticHint: "L’IA annote seule",
  tabConnections: "Connexions",
  tabConnectionsHint: "Ce qui tourne sur votre machine",
  close: "Fermer",

  listStartHere: "Commencez ici",
  familySam2: "SAM 2.1 · recommandé",
  familyMedsam2: "Domaine · imagerie médicale",
  familySam3: "SAM 3 · concepts",
  inUse: "utilisé",
  installed: "installé",
  recommended: "Recommandé",
  experimental: "Expérimental",
  modelsList: "Modèles disponibles",

  howTitle: "Comment ça marche",
  howHint: "Le connecteur, les modèles et votre image en un schéma",
  howIntro: "Poligome n’envoie d’image à aucun serveur. Le modèle est chargé et exécuté par un programme sur votre propre machine, et la page ne fait que lui parler.",
  howFindsTitle: "La page trouve, elle ne démarre jamais",
  howFindsBody: "À l’ouverture de l’éditeur, et à chaque retour sur l’onglet, la page cherche les programmes locaux et adopte ce qui est déjà chargé. Aucune page web ne peut lancer un processus ni démarrer un conteneur — c’est une règle du navigateur. C’est pourquoi la fenêtre de l’installateur doit rester ouverte, ou, sous Linux, pourquoi le service utilisateur la remplace.",
  howModesTitle: "Assisté et Automatique coexistent",
  howModesBody: "En Assisté, vous désignez l’objet — d’un clic, en traçant une boîte ou, avec SAM 3, en l’écrivant — et l’IA découpe seulement celui-ci. En Automatique, le modèle reçoit l’image et renvoie tout ce qu’il a trouvé. Les deux peuvent être prêts en même temps, et l’un ne modifie pas le résultat de l’autre.",
  howPrivacyTitle: "Inférence locale",
  howPrivacyBody: "Les images et les prompts restent sur l’ordinateur. Les conteneurs ne sont acceptés que sur 127.0.0.1 ou localhost : une adresse distante ferait sortir les images de votre machine, ce que Poligome évite justement.",

  autoGuideTitle: "Comment choisir",
  autoGuideHint: "Natif ou Conteneur, côte à côte",
  autoNativeSection: "Natifs · Poligome Runtime",
  autoNativeOffline: "Runtime introuvable",
  autoNativeOfflineHint: "Voir comment le connecter",
  autoMineSection: "Mes modèles · Conteneur",
  autoMineEmpty: "Aucun conteneur enregistré",
  autoAddModel: "Ajouter mon modèle",
  autoAddModelHint: "Docker · contrat et pas à pas",
  badgeNative: "Natif",
  badgeContainer: "Conteneur",
  stateUp: "actif",
  stateDown: "arrêté",

  guideIntro: "En Automatique, vous ne désignez rien : le modèle reçoit l’image et renvoie des annotations prêtes, avec ses propres classes. Il existe deux types de modèle, qui diffèrent par l’effort nécessaire pour les brancher et par ce qu’ils offrent en retour.",
  guideNativeTitle: "Natif — conçu pour Poligome",
  guideNativeBody: "Tourne sur Poligome Runtime, qui découpe l’image en parties. C’est pourquoi il supporte des orthophotos et des GeoTIFF énormes, dessine le résultat au fur et à mesure, accepte uniquement la région sélectionnée et propose des réglages à l’écran.",
  guideContainerTitle: "Conteneur — le modèle que vous avez déjà",
  guideContainerBody: "N’importe quel modèle dans un conteneur Docker respectant le contrat SageMaker. Le brancher est presque immédiat et le même conteneur sert ailleurs, mais il reçoit l’image entière d’un coup et le résultat n’apparaît qu’à la fin.",
  guideColumnNeed: "Ce dont vous avez besoin",
  guideRowLarge: "Images très grandes",
  guideRowRegion: "Seulement la région sélectionnée",
  guideRowParams: "Réglages à l’écran",
  guideRowLive: "Résultat pendant l’exécution",
  guideRowBatch: "Toutes les images du projet",
  guideRowEffort: "Effort pour le brancher",
  guideYes: "Oui",
  guideNo: "Non",
  guideLargeContainer: "Jusqu’à 16 MP",
  guideEffortNative: "Implémenter le protocole du runtime",
  guideEffortContainer: "Remplacer une fonction de l’exemple",
  guideRule: "En pratique : vous avez déjà un modèle et des photos de taille courante ? Conteneur. Vous travaillez sur des images énormes, ou voulez régler et relancer sans toucher au code ? Natif.",
  guideReview: "Dans les deux cas, le résultat entre dans le projet comme n’importe quelle annotation, et la fin de chaque exécution propose de tout annuler d’un coup.",

  nativeServedBy: "Servi par Poligome Runtime sur {endpoint}.",
  nativeVersion: "Version",
  nativeLicense: "Licence",
  nativeProduces: "Produit",
  nativeAccepts: "Accepte",
  nativeLarge: "Grandes images",
  nativeLargeValue: "Découpe en parties de {px} px maximum",
  nativeLargeWhole: "Reçoit l’image entière",
  nativeParams: "Réglages",
  nativeNoParams: "Ce modèle ne déclare aucun réglage.",
  nativeNone: "—",
  geomBox: "boîtes",
  geomPolygon: "polygones",
  geomPolyline: "lignes",
  geomKeypoint: "points",
  geomMask: "masques",
  promptRegion: "région",
  promptPoints: "points",
  promptBox: "boîte",
  promptText: "texte",
  runtimeOfflineTitle: "Aucun modèle natif connecté",
  runtimeOfflineBody: "Les modèles natifs tournent sur Poligome Runtime, un programme distinct du connecteur SAM. Dès qu’il tourne sur cette machine, le modèle qu’il sert apparaît ici de lui-même.",
  runtimeOfflineAddress: "La page cherche sur {endpoint}. Si votre runtime utilise un autre port, modifiez-le dans Connexions.",
  openConnections: "Ouvrir Connexions",
  usePreannotate: "Pré-annoter avec ce modèle",

  containerUp: "conteneur actif",
  containerDown: "conteneur arrêté",
  containerImage: "image {name}",
  containerLimits: "Limites déclarées par le modèle",
  containerClasses: "Classes exportées",
  containerParams: "Paramètres du modèle",
  containerEnv: "Environnement du conteneur",
  containerLastRun: "Dernière exécution",
  annotationOne: "{n} annotation",
  annotationMany: "{n} annotations",
  fieldName: "Nom",
  fieldPort: "Port",
  fieldNote: "Note",
  fieldNotePlaceholder: "À quoi il sert, sur quelles données il a été entraîné, ce qu’il faut relire avec attention.",
  cancel: "Annuler",
  save: "Enregistrer",
  saveFailed: "Impossible d’enregistrer : {detail}",
  editContainer: "Modifier le nom, le port et la note",
  removeContainer: "Supprimer l’enregistrement ; l’image et le conteneur restent dans Docker",
  containerStoppedHint: "Le conteneur est arrêté. Démarrez-le avec la commande start de la CLI BYOM, puis revenez sur cet écran.",
  byomNoMetadataReady: "Ce conteneur n’implémente pas GET /metadata et n’a pas encore tourné : il n’y a rien à décrire. Exécutez-le une fois sur une image.",
  byomNoMetadataDown: "Le conteneur est arrêté, il ne peut donc pas être décrit. Démarrez-le pour voir les classes qu’il exporte.",
  byomDeclares: "Déclare {n} classes : {list}.",
  byomDeclaresOne: "Déclare 1 classe : {list}.",
  byomObserved: "A renvoyé {n} classes lors de sa dernière exécution : {list}.",
  byomObservedOne: "A renvoyé 1 classe lors de sa dernière exécution : {list}.",
  byomExports: "Exporte {list}.",
  byomLastImage: "A produit {count} sur la dernière image.",
  listAnd: "et",

  connIntro: "Tout ce que l’IA utilise tourne sur votre machine. La page ne fait que trouver ces programmes ; les démarrer et les arrêter vous revient.",
  connConnectorTitle: "Connecteur local",
  connConnectorRole: "Sert le mode Assisté (SAM) et transmet aux modèles Conteneur.",
  connRuntimeTitle: "Poligome Runtime",
  connRuntimeRole: "Sert les modèles Natifs du mode Automatique.",
  connContainersTitle: "Conteneurs",
  connContainersRole: "Vos modèles dans Docker, joints via le connecteur.",
  connUp: "Connecté",
  connDown: "Introuvable",
  connChecking: "Vérification…",
  connServing: "Sert {model}",
  connHost: "Répond depuis {host}",
  connAddress: "Adresse",
  connRetry: "Vérifier à nouveau",
  connContainersCount: "{up} sur {total} actifs",
  connContainersNone: "Aucun conteneur enregistré.",
  connContainersNeedConnector: "Sans le connecteur, les conteneurs sont injoignables.",
  connConnectorHow: "Pour l’installer ou le démarrer, choisissez un modèle en mode Assisté : le pas à pas se trouve sur sa fiche.",
  connConnectorHowButton: "Voir l’installation",
  connContainersHowButton: "Voir comment en ajouter",
  connPortClash: "Le port 7861 est aussi celui du convertisseur COG par défaut. Si les deux tournent, un seul répond : changez le port de l’un d’eux, et l’adresse ici.",

  paSubtitle: "L’IA annote seule. Vous relisez et, si le résultat ne vous plaît pas, vous annulez tout d’un coup.",
  paModel: "Modèle",
  paWhere: "Où",
  paParams: "Réglages",
  paScopeImage: "Cette image",
  paScopeRegion: "Région sélectionnée",
  paScopeAll: "Toutes les images ({n})",
  paRegionNeedsBox: "Sélectionnez une boîte sur l’image pour l’utiliser comme région.",
  paRegionNativeOnly: "Seuls les modèles Natifs acceptent une région ; un Conteneur reçoit toujours l’image entière.",
  paLargeImage: "Cette image fait {mp} MP. Un modèle Conteneur reçoit l’image entière, et le connecteur refuse au-delà de 16 MP. Préférez un modèle Natif.",
  paNoModels: "Aucun modèle automatique disponible",
  paNoModelsHint: "Démarrez Poligome Runtime, lancez un conteneur ou ajoutez votre propre modèle.",
  paOpenHub: "Ouvrir les modèles d’IA",
  paStopped: "arrêté — démarrez le conteneur pour l’utiliser",
  paCapNative: "grandes images · région · réglages · progression",
  paCapContainer: "image entière · résultat à la fin",
  paNoImage: "Ouvrez une image avant de pré-annoter.",
  paBusy: "Une pré-annotation est déjà en cours.",

  progressLabel: "Pré-annotation avec {model}",
  progressImage: "image {i} sur {n}",
  progressTiles: "partie {done} sur {total}",
  progressCancel: "Annuler",

  sumDone: "Pré-annotation terminée : {count}",
  sumDoneImages: "Pré-annotation terminée : {count} sur {images} images",
  sumCanceled: "Pré-annotation annulée : {count} étaient déjà arrivées",
  sumFailed: "Échec sur {names}.",
  sumReview: "Les annotations sont déjà dans le projet. Relisez-les avant d’exporter.",
  sumKeep: "Garder",
  sumUndo: "Annuler la pré-annotation",
  sumUndone: "Pré-annotation annulée : {count} supprimées.",
  sumNone: "{model} n’a renvoyé aucune annotation.",
  sumReplaced: "{n} annotations précédentes du même modèle ont été remplacées.",

  runRegion: "{model} : région {w}×{h}…",
  runWorking: "{model} : annotation en cours…",
  runNoCoco: "{model} : le conteneur a répondu sans document COCO.",
  runHttp: "{model} : HTTP {status}",
  runRuntimeError: "Poligome Runtime : {detail}",
  runRuntimeUnreachable: "Poligome Runtime n’a pas répondu. C’est un programme distinct du connecteur SAM : vérifiez dans Modèles d’IA › Connexions qu’il tourne à l’adresse configurée.",
  runConnectorUnreachable: "Le connecteur local n’a pas répondu, et c’est par lui que l’on joint les modèles Conteneur. Vérifiez dans Modèles d’IA › Connexions.",
};

const es: AiCopy = {
  aiButton: "IA",
  aiHintSam: "Asistido: {model}",
  aiHintRuntime: "Nativo: {model}",
  aiHintContainers: "Contenedores activos: {n}",
  aiHintNone: "Ningún modelo de IA conectado. Haz clic para configurarlo.",
  preAnnotate: "Pre-anotar",
  preAnnotateHint: "La IA anota sola la imagen, una región o todo el proyecto",

  hubTitle: "Modelos de IA",
  hubSubtitle: "Asistido: tú señalas y la IA recorta. Automático: la IA anota sola y tú revisas.",
  tabAssisted: "Asistido",
  tabAssistedHint: "Tú señalas, la IA recorta",
  tabAutomatic: "Automático",
  tabAutomaticHint: "La IA anota sola",
  tabConnections: "Conexiones",
  tabConnectionsHint: "Lo que corre en tu máquina",
  close: "Cerrar",

  listStartHere: "Empieza aquí",
  familySam2: "SAM 2.1 · recomendado",
  familyMedsam2: "Dominio · imagen médica",
  familySam3: "SAM 3 · conceptos",
  inUse: "en uso",
  installed: "instalado",
  recommended: "Recomendado",
  experimental: "Experimental",
  modelsList: "Modelos disponibles",

  howTitle: "Cómo funciona",
  howHint: "El conector, los modelos y tu imagen en un dibujo",
  howIntro: "Poligome no envía imágenes a ningún servidor. Quien carga el modelo y ejecuta la inferencia es un programa en tu propia máquina, y la página solo habla con él.",
  howFindsTitle: "La página encuentra, nunca enciende",
  howFindsBody: "Al abrir el editor, y cada vez que vuelves a la pestaña, la página busca los programas locales y adopta lo que ya esté cargado. Ninguna página web puede iniciar un proceso ni levantar un contenedor: es una regla del navegador. Por eso la ventana del instalador debe quedar abierta o, en Linux, el servicio de usuario cumple ese papel.",
  howModesTitle: "Asistido y Automático conviven",
  howModesBody: "En Asistido señalas el objeto — con un clic, arrastrando una caja o, en SAM 3, escribiendo — y la IA recorta solo ese. En Automático el modelo recibe la imagen y devuelve todo lo que encontró. Los dos pueden estar listos a la vez, y uno no altera el resultado del otro.",
  howPrivacyTitle: "Inferencia local",
  howPrivacyBody: "Las imágenes y los prompts se quedan en el ordenador. Los contenedores solo se aceptan en 127.0.0.1 o localhost: una dirección remota sacaría las imágenes de tu máquina, que es justo lo que Poligome evita.",

  autoGuideTitle: "Cómo elegir",
  autoGuideHint: "Nativo o Contenedor, lado a lado",
  autoNativeSection: "Nativos · Poligome Runtime",
  autoNativeOffline: "Runtime no encontrado",
  autoNativeOfflineHint: "Ver cómo conectarlo",
  autoMineSection: "Mis modelos · Contenedor",
  autoMineEmpty: "Ningún contenedor registrado",
  autoAddModel: "Añadir mi modelo",
  autoAddModelHint: "Docker · contrato y paso a paso",
  badgeNative: "Nativo",
  badgeContainer: "Contenedor",
  stateUp: "activo",
  stateDown: "detenido",

  guideIntro: "En Automático no señalas nada: el modelo recibe la imagen y devuelve las anotaciones listas, con sus propias clases. Hay dos tipos de modelo, y se diferencian en cuánto trabajo cuesta conectarlos y en lo que ganas a cambio.",
  guideNativeTitle: "Nativo — hecho para Poligome",
  guideNativeBody: "Corre en Poligome Runtime, que divide la imagen en partes. Por eso aguanta ortofotos y GeoTIFF enormes, dibuja el resultado mientras avanza, acepta solo la región que seleccionaste y ofrece ajustes en pantalla.",
  guideContainerTitle: "Contenedor — el modelo que ya tienes",
  guideContainerBody: "Cualquier modelo en un contenedor Docker con el contrato de SageMaker. Conectarlo es casi inmediato y el mismo contenedor sirve en otros lugares, pero recibe la imagen entera de una vez y el resultado solo aparece al final.",
  guideColumnNeed: "Lo que necesitas",
  guideRowLarge: "Imágenes muy grandes",
  guideRowRegion: "Solo la región seleccionada",
  guideRowParams: "Ajustes en pantalla",
  guideRowLive: "Resultado mientras corre",
  guideRowBatch: "Todas las imágenes del proyecto",
  guideRowEffort: "Esfuerzo para conectarlo",
  guideYes: "Sí",
  guideNo: "No",
  guideLargeContainer: "Hasta 16 MP",
  guideEffortNative: "Implementar el protocolo del runtime",
  guideEffortContainer: "Cambiar una función del ejemplo",
  guideRule: "Regla práctica: ¿ya tienes un modelo y fotos de tamaño normal? Contenedor. ¿Trabajas con imágenes enormes o quieres ajustar y volver a correr sin tocar código? Nativo.",
  guideReview: "En los dos casos el resultado entra en el proyecto como cualquier anotación, y el final de cada ejecución ofrece deshacerlo todo de una vez.",

  nativeServedBy: "Servido por Poligome Runtime en {endpoint}.",
  nativeVersion: "Versión",
  nativeLicense: "Licencia",
  nativeProduces: "Produce",
  nativeAccepts: "Acepta",
  nativeLarge: "Imágenes grandes",
  nativeLargeValue: "Divide en partes de hasta {px} px",
  nativeLargeWhole: "Recibe la imagen entera",
  nativeParams: "Ajustes",
  nativeNoParams: "Este modelo no declara ajustes.",
  nativeNone: "—",
  geomBox: "cajas",
  geomPolygon: "polígonos",
  geomPolyline: "líneas",
  geomKeypoint: "puntos",
  geomMask: "máscaras",
  promptRegion: "región",
  promptPoints: "puntos",
  promptBox: "caja",
  promptText: "texto",
  runtimeOfflineTitle: "Ningún modelo nativo conectado",
  runtimeOfflineBody: "Los modelos nativos corren en Poligome Runtime, un programa separado del conector de SAM. Cuando esté corriendo en esta máquina, el modelo que sirve aparece aquí solo.",
  runtimeOfflineAddress: "La página busca en {endpoint}. Si tu runtime usa otro puerto, cámbialo en Conexiones.",
  openConnections: "Abrir Conexiones",
  usePreannotate: "Pre-anotar con este modelo",

  containerUp: "contenedor activo",
  containerDown: "contenedor detenido",
  containerImage: "imagen {name}",
  containerLimits: "Limitaciones declaradas por el modelo",
  containerClasses: "Clases exportadas",
  containerParams: "Parámetros del modelo",
  containerEnv: "Entorno del contenedor",
  containerLastRun: "Última ejecución",
  annotationOne: "{n} anotación",
  annotationMany: "{n} anotaciones",
  fieldName: "Nombre",
  fieldPort: "Puerto",
  fieldNote: "Nota",
  fieldNotePlaceholder: "Para qué sirve, con qué datos se entrenó, qué revisar con cuidado.",
  cancel: "Cancelar",
  save: "Guardar",
  saveFailed: "No se pudo guardar: {detail}",
  editContainer: "Editar nombre, puerto y nota",
  removeContainer: "Quitar el registro; la imagen y el contenedor siguen en Docker",
  containerStoppedHint: "El contenedor está detenido. Levántalo con el comando start de la CLI de BYOM y vuelve a esta pantalla.",
  byomNoMetadataReady: "Este contenedor no implementa GET /metadata y todavía no se ejecutó, así que no hay nada que describir. Ejecútalo una vez sobre una imagen.",
  byomNoMetadataDown: "El contenedor está detenido, así que no se puede describir. Levántalo para ver las clases que exporta.",
  byomDeclares: "Declara {n} clases: {list}.",
  byomDeclaresOne: "Declara 1 clase: {list}.",
  byomObserved: "En la última ejecución devolvió {n} clases: {list}.",
  byomObservedOne: "En la última ejecución devolvió 1 clase: {list}.",
  byomExports: "Exporta {list}.",
  byomLastImage: "En la última imagen produjo {count}.",
  listAnd: "y",

  connIntro: "Todo lo que usa la IA corre en tu máquina. La página solo encuentra estos programas; encenderlos y apagarlos queda en tus manos.",
  connConnectorTitle: "Conector local",
  connConnectorRole: "Atiende el modo Asistido (SAM) y reenvía a los modelos Contenedor.",
  connRuntimeTitle: "Poligome Runtime",
  connRuntimeRole: "Atiende los modelos Nativos del modo Automático.",
  connContainersTitle: "Contenedores",
  connContainersRole: "Tus modelos en Docker, alcanzados a través del conector.",
  connUp: "Conectado",
  connDown: "No encontrado",
  connChecking: "Comprobando…",
  connServing: "Sirviendo {model}",
  connHost: "Atendiendo desde {host}",
  connAddress: "Dirección",
  connRetry: "Comprobar de nuevo",
  connContainersCount: "{up} de {total} activos",
  connContainersNone: "Ningún contenedor registrado.",
  connContainersNeedConnector: "Sin el conector, los contenedores no se alcanzan.",
  connConnectorHow: "Para instalarlo o iniciarlo, elige un modelo en el modo Asistido: el paso a paso está en su ficha.",
  connConnectorHowButton: "Ver instalación",
  connContainersHowButton: "Ver cómo añadir uno",
  connPortClash: "El puerto 7861 también es el predeterminado del conversor de COG. Si los dos están corriendo, solo uno responde: cambia el puerto de uno de ellos, y la dirección aquí.",

  paSubtitle: "La IA anota sola. Tú revisas y, si no te gusta, lo deshaces todo de una vez.",
  paModel: "Modelo",
  paWhere: "Dónde",
  paParams: "Ajustes",
  paScopeImage: "Esta imagen",
  paScopeRegion: "Región seleccionada",
  paScopeAll: "Todas las imágenes ({n})",
  paRegionNeedsBox: "Selecciona una caja en la imagen para usarla como región.",
  paRegionNativeOnly: "Solo los modelos Nativos reciben una región; un Contenedor siempre recibe la imagen entera.",
  paLargeImage: "Esta imagen tiene {mp} MP. Un modelo Contenedor recibe la imagen entera, y el conector rechaza más de 16 MP. Prefiere un modelo Nativo.",
  paNoModels: "Ningún modelo automático disponible",
  paNoModelsHint: "Inicia Poligome Runtime, levanta un contenedor o añade tu propio modelo.",
  paOpenHub: "Abrir modelos de IA",
  paStopped: "detenido — levanta el contenedor para usarlo",
  paCapNative: "imágenes grandes · región · ajustes · progreso",
  paCapContainer: "imagen entera · resultado al final",
  paNoImage: "Abre una imagen antes de pre-anotar.",
  paBusy: "Ya hay una pre-anotación en curso.",

  progressLabel: "Pre-anotando con {model}",
  progressImage: "imagen {i} de {n}",
  progressTiles: "parte {done} de {total}",
  progressCancel: "Cancelar",

  sumDone: "Pre-anotación terminada: {count}",
  sumDoneImages: "Pre-anotación terminada: {count} en {images} imágenes",
  sumCanceled: "Pre-anotación cancelada: {count} ya habían llegado",
  sumFailed: "Falló en {names}.",
  sumReview: "Las anotaciones ya están en el proyecto. Revísalas antes de exportar.",
  sumKeep: "Mantener",
  sumUndo: "Deshacer pre-anotación",
  sumUndone: "Pre-anotación deshecha: {count} eliminadas.",
  sumNone: "{model} no devolvió ninguna anotación.",
  sumReplaced: "Se reemplazaron {n} anteriores del mismo modelo.",

  runRegion: "{model}: región {w}×{h}…",
  runWorking: "{model}: anotando…",
  runNoCoco: "{model}: el contenedor respondió sin documento COCO.",
  runHttp: "{model}: HTTP {status}",
  runRuntimeError: "Poligome Runtime: {detail}",
  runRuntimeUnreachable: "Poligome Runtime no respondió. Es un programa separado del conector de SAM: comprueba en Modelos de IA › Conexiones que esté corriendo en la dirección configurada.",
  runConnectorUnreachable: "El conector local no respondió, y es a través de él que se alcanzan los modelos Contenedor. Compruébalo en Modelos de IA › Conexiones.",
};

const translations: Record<Language, AiCopy> = { pt, en, fr, es };

export function getAiCopy(language: Language): AiCopy {
  return translations[language];
}

/** "{n} anotação" ou "{n} anotações", já preenchido. */
export function countAnnotations(copy: AiCopy, n: number): string {
  return (n === 1 ? copy.annotationOne : copy.annotationMany).replace("{n}", String(n));
}

/** "a, b e c" no idioma pedido. */
export function joinList(copy: AiCopy, items: readonly string[]): string {
  if (items.length <= 1) return items.join("");
  return `${items.slice(0, -1).join(", ")} ${copy.listAnd} ${items[items.length - 1]}`;
}
