import type { Language } from "./i18n";

/**
 * Os textos da aba Assistido (a ficha de cada SAM e a instalação) e do guia
 * "Adicionar meu modelo" do BYOM.
 *
 * Regra de escrita: direto e curto — o passo e o comando, sem justificativa. O
 * porquê de cada passo está em docs/sam.md e docs/byom.md.
 *
 * Trechos entre crases viram `<code>` na tela: assim uma frase com nome de
 * arquivo ou comando continua inteira em cada idioma. `{nome}` é preenchido
 * com `fill`.
 */
const pt = {
  capImage: "Imagem",
  capVideo: "Vídeo",
  capPoints: "Pontos",
  capNegativePoints: "Pontos negativos",
  capBoxes: "Caixas",
  capMask: "Máscara anterior",
  capText: "Texto",
  capExemplars: "Exemplos",
  capAutoMasks: "Máscaras automáticas",
  capMultimask: "Várias opções",
  capRefine: "Refinamento",
  capInstances: "Instâncias",
  capConcepts: "Conceitos",
  capTracking: "Rastreamento",
  capMultiObject: "Vários objetos",
  capBidirectional: "Propagação nos dois sentidos",

  stChecking: "Procurando o conector…",
  stLoading: "Carregando o modelo…",
  stError: "O modelo não carregou",
  stReady: "Pronto",
  stOtherLoaded: "Outro modelo está carregado",
  stOffline: "Conector desligado",
  stSwitchRefused: "Troca de modelo recusada",
  stStillUp: "Continua com {label}.",
  stErrorHint: "Confira checkpoint, CUDA e dependências, e reinicie o conector.",
  stMismatchHint: "Clique em “Carregar este modelo” para trocar para `{id}`.",
  stHost: "Em",
  stOfflineHint: "Instale ou inicie o conector (passo a passo nesta ficha).",
  btnLoading: "Carregando…",
  btnUse: "Usar este modelo",
  btnLoad: "Carregar este modelo",
  btnVerify: "Verificar e usar",
  unselect: "Parar de usar o SAM",
  unselectHint: "Nada é desinstalado.",

  benchFps: "{fps} FPS em vídeo",
  benchSam3: "Imagem com mais de 100 objetos (benchmark da Meta)",
  benchNone: "Sem número comparável",
  benchDisclaimer: "Referência oficial, não previsão para sua GPU.",

  factCheckpoint: "checkpoint",
  factParams: "parâmetros",
  factLicense: "licença",
  experimental: "Experimental",
  capsHere: "Disponível aqui",
  capsPending: "O modelo faz, o editor ainda não",
  capsVideoNote: "Vídeo ainda não: o editor abre só imagens.",
  citation: "Referência",
  readPaper: "Ler o artigo",
  futureTitle: "{name} · em breve",
  futureNote: "Ainda não disponível aqui. Oficial: {speedup} em {hardware}.",
  reqStack: "Software",
  reqCompute: "Processamento",
  reqCuda: "CUDA",
  cudaRequired: "Obrigatório: CUDA {version}+",
  cudaOptional: "Opcional; GPU recomendada",
  cudaTested: " · testado: {version}",
  reqSystem: "Sistema",
  reqMemory: "Memória",
  reqAccess: "Acesso",
  licenseWarning: "Licença e acesso restritos",

  installTitle: "Instalar",
  installBody: "Baixa só o checkpoint escolhido. O primeiro modelo de cada família baixa alguns GB de bibliotecas.",
  needsInstall: "{name} não está instalado.",
  needsInstallBody: "Rode o comando abaixo e volte aqui.",
  osPicker: "Sistema operacional",
  osUnix: "Linux ou macOS",
  osWsl: "Windows (WSL2)",
  osNative: "Windows",
  sam3NoMac: "SAM 3 exige CUDA: não roda no macOS.",
  sam3Native: "SAM 3 exige GPU NVIDIA com CUDA. O instalador confere antes de baixar.",
  download: "Baixar {file}",
  stepDownloadTitle: "Baixe o instalador",
  stepDownloadUnix: "Ele vai para a pasta Downloads.",
  stepDownloadWin: "Ele vai para a pasta Downloads.",
  stepUnixTerminalTitle: "Abra o Terminal na pasta Downloads",
  stepUnixTerminalBody: "Ubuntu: Ctrl+Alt+T. macOS: Spotlight › Terminal.",
  stepUnixRunTitle: "Rode o instalador",
  stepUnixRunBody: "Termina com “instalado, carregado e selecionado”.",
  stepUnixKeepTitle: "Deixe o Terminal aberto",
  stepUnixKeepBody: "Fechou? A IA desliga. Use o iniciador abaixo para religar.",
  stepBackTitle: "Clique em “Verificar e usar”",
  stepBackBody: "O status no rodapé fica verde.",
  stepWslClickTitle: "Dê dois cliques no arquivo",
  stepWslClickBody: "Digite o número do modelo e tecle Enter.",
  stepWslTypeTitle: "Ou pelo Prompt de Comando",
  stepWslTypeBody: "Na pasta Downloads:",
  stepWslKeepTitle: "Deixe a janela aberta",
  stepWslKeepBody: "Fechou? A IA desliga.",
  stepNativeOpenTitle: "Abra o PowerShell",
  stepNativeOpenBody: "Pelo menu Iniciar. Não dê dois cliques no arquivo.",
  stepNativeFolderTitle: "Vá para a pasta Downloads",
  stepNativeFolderBody: "",
  stepNativeRunTitle: "Rode o instalador",
  stepNativeRunBody: "Use o comando completo.",
  stepNativeKeepTitle: "Deixe o PowerShell aberto",
  stepNativeKeepBody: "Fechou? A IA desliga.",
  cpuTitle: "Usar só CPU",
  cpuBody: "Para não usar a placa de vídeo, ou se ela for antiga. Mais lento. Muda os comandos acima.",
  relaunchTitle: "Para religar depois",
  relaunchUnix: "Use o iniciador. Não baixa nada de novo.",
  relaunchService: "No Linux, o serviço religa sozinho a cada login:",
  relaunchWsl: "Dois cliques no iniciador. Não baixa nada de novo.",
  relaunchWslCpu: "Com CPU marcado, use o Prompt de Comando:",
  relaunchNative: "Rode o mesmo comando de novo.",
  sam3GpuOnly: "SAM 3 só roda em GPU NVIDIA.",
  oldGpuNote: "Placa antiga demais? O instalador avisa antes de baixar.",
  platformDetails: "Detalhes por sistema",
  uninstallTitle: "Desinstalar",
  uninstallBody: "Feche o conector e apague a pasta abaixo. Nada fica em outro lugar.",
  uninstallUnix: "Linux e macOS",
  uninstallNative: "Windows",
  uninstallWsl: "Windows (WSL2)",
  uninstallWslBody: "`wsl rm -rf ~/.poligome-sam`",
  uninstallService: "Linux com serviço: antes, `poligome-sam-service-linux.sh uninstall`. Contêineres BYOM: `docker rm -f`.",
  officialLinks: "Links oficiais",
  officialRepo: "Repositório",
  officialCheckpoint: "Checkpoint",
  privacyTitle: "Privacidade",
  samPrivacy: "Imagens e prompts ficam no computador.",

  byomBadge: "Docker",
  byomTitle: "Adicionar meu modelo",
  byomIntro: "Seu modelo num contêiner Docker. Ele recebe a imagem e devolve anotações em COCO.",
  byomSagemaker: "Mesmo contrato do SageMaker: comando `serve`, porta 8080, `GET /ping` e `POST /invocations`. Pesos em `/opt/ml/model`.",
  byomBefore: "Antes de começar",
  byomDockerTitle: "Docker ligado",
  byomDockerBody: "O Poligome não instala nem liga o Docker.",
  byomConnectorTitle: "Conector ligado",
  byomConnectorBody: "O editor chega ao contêiner pelo conector. Instale pela aba Assistido.",
  byomWindowsTitle: "No Windows",
  byomWindowsBody: "Conector instalado pelo `.bat` (WSL2): use a CLI bash dentro do WSL. Pelo `.ps1`: use a CLI do PowerShell.",
  byomContract: "Contrato",
  byomPort: "Porta",
  byomPortValue: "`8080`",
  byomCommand: "Comando",
  byomHealth: "Pronto",
  byomHealthValue: "`GET /ping` → 200",
  byomInference: "Inferência",
  byomInferenceValue: "`POST /invocations` → COCO",
  byomWeights: "Pesos",
  byomWeightsValue: "`/opt/ml/model`",
  byomDescription: "Descrição",
  byomDescriptionValue: "`GET /metadata` (opcional)",
  byomInput: "Entrada:",
  byomInputValue: "`{ image, file_name, width, height }`",
  byomOutput: "Saída:",
  byomOutputValue: "COCO. Cada anotação precisa de `segmentation` (lista de pontos, sem RLE), `bbox` ou `keypoints`. `category_id` vira a classe.",
  byomErrors: "Erros:",
  byomErrorsValue: "`{ \"detail\": \"mensagem\" }` — aparece na tela.",
  byomMetadataHint: "Com `/metadata`, a ficha mostra as classes antes da primeira execução.",
  byomFiles: "Arquivos",
  byomFilesBody: "O serve.py de exemplo já cumpre o contrato. Troque só a função predict().",
  byomCliUnix: "CLI · Linux, macOS, WSL2",
  byomCliNative: "CLI · Windows",
  byomCliNativeHint: "PowerShell",
  byomDockerfile: "Dockerfile",
  byomDockerfileHint: "exemplo",
  byomServe: "serve.py",
  byomServeHint: "exemplo",
  byomExamples: "Testar com os exemplos",
  byomRepoTitle: "Com o repositório clonado",
  byomRepoBody: "Cria e registra dois modelos de exemplo (portas 8080 e 8081).",
  byomFilesOnlyTitle: "Só com os arquivos baixados",
  byomFilesOnlyBody: "Construa a imagem e registre os dois modelos:",
  byomCheckTitle: "Conferir",
  byomCheckBody: "list mostra o estado; logs mostra o erro.",
  byomSteps: "Passo a passo",
  byomStepsShell: "Comandos em bash. No Windows, use `poligome-byom-windows.ps1` com os mesmos comandos.",
  byomStep1Title: "1. Baixe os arquivos",
  byomStep1Body: "Troque a função predict() do serve.py pelo seu modelo.",
  byomStep1Comment: "# pasta dos arquivos",
  byomStep2Title: "2. Construa a imagem",
  byomStep2Body: "",
  byomStep3Title: "3. Registre",
  byomStep3Body: "O identificador começa com byom-.",
  byomStep4Title: "4. Inicie",
  byomStep4Body: "Aparece na lista quando o /ping responder.",
  byomStep5Title: "5. Depois de reiniciar o computador",
  byomStep5Body: "Inicie de novo. Para iniciar com o Docker: docker update --restart unless-stopped.",
  byomImportTitle: "Importar contêiner já rodando",
  byomImportHint: "Só registra o endereço. O contêiner precisa estar no ar.",
  byomFieldId: "Identificador",
  byomFieldName: "Nome",
  byomFieldPort: "Porta",
  byomNamePlaceholder: "Meu modelo",
  byomImporting: "Importando…",
  byomImport: "Importar",
  byomIdRule: "Comece com `byom-` e use só minúsculas, números, `.`, `-` ou `_`.",
  byomImportFailed: "Não foi possível importar: {detail}",
  byomNoneRegistered: "Nenhum contêiner ainda.",
  byomOneRegistered: "1 modelo registrado.",
  byomManyRegistered: "{n} modelos registrados.",
  byomEmptyTitle: "Não aparece?",
  byomEmptyBody: "Lista vazia: conector desligado. Modelo parado: veja `logs` (geralmente porta ocupada).",
  byomPrivacy: "Só `127.0.0.1` ou `localhost`: a imagem não sai do computador.",
};

export type SamCopy = Record<keyof typeof pt, string>;

const en: SamCopy = {
  capImage: "Image",
  capVideo: "Video",
  capPoints: "Points",
  capNegativePoints: "Negative points",
  capBoxes: "Boxes",
  capMask: "Previous mask",
  capText: "Text",
  capExemplars: "Examples",
  capAutoMasks: "Automatic masks",
  capMultimask: "Several options",
  capRefine: "Refinement",
  capInstances: "Instances",
  capConcepts: "Concepts",
  capTracking: "Tracking",
  capMultiObject: "Multiple objects",
  capBidirectional: "Two-way propagation",

  stChecking: "Looking for the connector…",
  stLoading: "Loading the model…",
  stError: "The model did not load",
  stReady: "Ready",
  stOtherLoaded: "Another model is loaded",
  stOffline: "Connector off",
  stSwitchRefused: "Model switch refused",
  stStillUp: "Still running {label}.",
  stErrorHint: "Check the checkpoint, CUDA and dependencies, then restart the connector.",
  stMismatchHint: "Click “Load this model” to switch to `{id}`.",
  stHost: "On",
  stOfflineHint: "Install or start the connector (steps on this card).",
  btnLoading: "Loading…",
  btnUse: "Use this model",
  btnLoad: "Load this model",
  btnVerify: "Check and use",
  unselect: "Stop using SAM",
  unselectHint: "Nothing is uninstalled.",

  benchFps: "{fps} video FPS",
  benchSam3: "Image with over 100 objects (Meta benchmark)",
  benchNone: "No comparable figure",
  benchDisclaimer: "Official reference, not a forecast for your GPU.",

  factCheckpoint: "checkpoint",
  factParams: "parameters",
  factLicense: "license",
  experimental: "Experimental",
  capsHere: "Available here",
  capsPending: "The model does it, the editor not yet",
  capsVideoNote: "No video yet: the editor opens images only.",
  citation: "Reference",
  readPaper: "Read the paper",
  futureTitle: "{name} · coming",
  futureNote: "Not available here yet. Official: {speedup} on {hardware}.",
  reqStack: "Software",
  reqCompute: "Compute",
  reqCuda: "CUDA",
  cudaRequired: "Required: CUDA {version}+",
  cudaOptional: "Optional; GPU recommended",
  cudaTested: " · tested: {version}",
  reqSystem: "System",
  reqMemory: "Memory",
  reqAccess: "Access",
  licenseWarning: "Restricted license and access",

  installTitle: "Install",
  installBody: "Downloads only the chosen checkpoint. The first model of each family downloads a few GB of libraries.",
  needsInstall: "{name} is not installed.",
  needsInstallBody: "Run the command below and come back.",
  osPicker: "Operating system",
  osUnix: "Linux or macOS",
  osWsl: "Windows (WSL2)",
  osNative: "Windows",
  sam3NoMac: "SAM 3 needs CUDA: it does not run on macOS.",
  sam3Native: "SAM 3 needs an NVIDIA GPU with CUDA. The installer checks before downloading.",
  download: "Download {file}",
  stepDownloadTitle: "Download the installer",
  stepDownloadUnix: "It goes to your Downloads folder.",
  stepDownloadWin: "It goes to your Downloads folder.",
  stepUnixTerminalTitle: "Open the Terminal in Downloads",
  stepUnixTerminalBody: "Ubuntu: Ctrl+Alt+T. macOS: Spotlight › Terminal.",
  stepUnixRunTitle: "Run the installer",
  stepUnixRunBody: "It ends with “installed, loaded and selected”.",
  stepUnixKeepTitle: "Keep the Terminal open",
  stepUnixKeepBody: "Closed it? The AI turns off. Use the launcher below to restart.",
  stepBackTitle: "Click “Check and use”",
  stepBackBody: "The footer status turns green.",
  stepWslClickTitle: "Double-click the file",
  stepWslClickBody: "Type the model number and press Enter.",
  stepWslTypeTitle: "Or use the Command Prompt",
  stepWslTypeBody: "In the Downloads folder:",
  stepWslKeepTitle: "Keep the window open",
  stepWslKeepBody: "Closed it? The AI turns off.",
  stepNativeOpenTitle: "Open PowerShell",
  stepNativeOpenBody: "From the Start menu. Do not double-click the file.",
  stepNativeFolderTitle: "Go to the Downloads folder",
  stepNativeFolderBody: "",
  stepNativeRunTitle: "Run the installer",
  stepNativeRunBody: "Use the full command.",
  stepNativeKeepTitle: "Keep PowerShell open",
  stepNativeKeepBody: "Closed it? The AI turns off.",
  cpuTitle: "CPU only",
  cpuBody: "To skip the graphics card, or if it is too old. Slower. Changes the commands above.",
  relaunchTitle: "To restart later",
  relaunchUnix: "Use the launcher. Nothing is downloaded again.",
  relaunchService: "On Linux, the service restarts it at every login:",
  relaunchWsl: "Double-click the launcher. Nothing is downloaded again.",
  relaunchWslCpu: "With CPU ticked, use the Command Prompt:",
  relaunchNative: "Run the same command again.",
  sam3GpuOnly: "SAM 3 only runs on an NVIDIA GPU.",
  oldGpuNote: "Card too old? The installer warns before downloading.",
  platformDetails: "Details per system",
  uninstallTitle: "Uninstall",
  uninstallBody: "Close the connector and delete the folder below. Nothing is left anywhere else.",
  uninstallUnix: "Linux and macOS",
  uninstallNative: "Windows",
  uninstallWsl: "Windows (WSL2)",
  uninstallWslBody: "`wsl rm -rf ~/.poligome-sam`",
  uninstallService: "Linux with the service: first `poligome-sam-service-linux.sh uninstall`. BYOM containers: `docker rm -f`.",
  officialLinks: "Official links",
  officialRepo: "Repository",
  officialCheckpoint: "Checkpoint",
  privacyTitle: "Privacy",
  samPrivacy: "Images and prompts stay on the computer.",

  byomBadge: "Docker",
  byomTitle: "Add my model",
  byomIntro: "Your model in a Docker container. It receives the image and returns COCO annotations.",
  byomSagemaker: "Same contract as SageMaker: `serve` command, port 8080, `GET /ping` and `POST /invocations`. Weights in `/opt/ml/model`.",
  byomBefore: "Before you start",
  byomDockerTitle: "Docker running",
  byomDockerBody: "Poligome does not install or start Docker.",
  byomConnectorTitle: "Connector running",
  byomConnectorBody: "The editor reaches the container through the connector. Install it from the Assisted tab.",
  byomWindowsTitle: "On Windows",
  byomWindowsBody: "Connector installed with the `.bat` (WSL2): use the bash CLI inside WSL. With the `.ps1`: use the PowerShell CLI.",
  byomContract: "Contract",
  byomPort: "Port",
  byomPortValue: "`8080`",
  byomCommand: "Command",
  byomHealth: "Ready",
  byomHealthValue: "`GET /ping` → 200",
  byomInference: "Inference",
  byomInferenceValue: "`POST /invocations` → COCO",
  byomWeights: "Weights",
  byomWeightsValue: "`/opt/ml/model`",
  byomDescription: "Description",
  byomDescriptionValue: "`GET /metadata` (optional)",
  byomInput: "Input:",
  byomInputValue: "`{ image, file_name, width, height }`",
  byomOutput: "Output:",
  byomOutputValue: "COCO. Each annotation needs `segmentation` (point list, no RLE), `bbox` or `keypoints`. `category_id` becomes the class.",
  byomErrors: "Errors:",
  byomErrorsValue: "`{ \"detail\": \"message\" }` — shown on screen.",
  byomMetadataHint: "With `/metadata`, the card shows the classes before the first run.",
  byomFiles: "Files",
  byomFilesBody: "The example serve.py already follows the contract. Replace only the predict() function.",
  byomCliUnix: "CLI · Linux, macOS, WSL2",
  byomCliNative: "CLI · Windows",
  byomCliNativeHint: "PowerShell",
  byomDockerfile: "Dockerfile",
  byomDockerfileHint: "example",
  byomServe: "serve.py",
  byomServeHint: "example",
  byomExamples: "Try the examples",
  byomRepoTitle: "With the repository cloned",
  byomRepoBody: "Builds and registers two example models (ports 8080 and 8081).",
  byomFilesOnlyTitle: "With the downloaded files only",
  byomFilesOnlyBody: "Build the image and register both models:",
  byomCheckTitle: "Check",
  byomCheckBody: "list shows the status; logs shows the error.",
  byomSteps: "Step by step",
  byomStepsShell: "Commands in bash. On Windows, use `poligome-byom-windows.ps1` with the same commands.",
  byomStep1Title: "1. Download the files",
  byomStep1Body: "Replace the predict() function in serve.py with your model.",
  byomStep1Comment: "# files folder",
  byomStep2Title: "2. Build the image",
  byomStep2Body: "",
  byomStep3Title: "3. Register",
  byomStep3Body: "The identifier starts with byom-.",
  byomStep4Title: "4. Start",
  byomStep4Body: "It shows up in the list once /ping answers.",
  byomStep5Title: "5. After restarting the computer",
  byomStep5Body: "Start it again. To start with Docker: docker update --restart unless-stopped.",
  byomImportTitle: "Import a running container",
  byomImportHint: "Only records the address. The container must be up.",
  byomFieldId: "Identifier",
  byomFieldName: "Name",
  byomFieldPort: "Port",
  byomNamePlaceholder: "My model",
  byomImporting: "Importing…",
  byomImport: "Import",
  byomIdRule: "Start with `byom-` and use only lowercase letters, digits, `.`, `-` or `_`.",
  byomImportFailed: "Could not import: {detail}",
  byomNoneRegistered: "No containers yet.",
  byomOneRegistered: "1 model registered.",
  byomManyRegistered: "{n} models registered.",
  byomEmptyTitle: "Not showing up?",
  byomEmptyBody: "Empty list: the connector is off. Stopped model: check `logs` (usually a busy port).",
  byomPrivacy: "Only `127.0.0.1` or `localhost`: the image never leaves the computer.",
};

const fr: SamCopy = {
  capImage: "Image",
  capVideo: "Vidéo",
  capPoints: "Points",
  capNegativePoints: "Points négatifs",
  capBoxes: "Boîtes",
  capMask: "Masque précédent",
  capText: "Texte",
  capExemplars: "Exemples",
  capAutoMasks: "Masques automatiques",
  capMultimask: "Plusieurs options",
  capRefine: "Affinage",
  capInstances: "Instances",
  capConcepts: "Concepts",
  capTracking: "Suivi",
  capMultiObject: "Plusieurs objets",
  capBidirectional: "Propagation dans les deux sens",

  stChecking: "Recherche du connecteur…",
  stLoading: "Chargement du modèle…",
  stError: "Le modèle ne s’est pas chargé",
  stReady: "Prêt",
  stOtherLoaded: "Un autre modèle est chargé",
  stOffline: "Connecteur arrêté",
  stSwitchRefused: "Changement de modèle refusé",
  stStillUp: "Toujours sur {label}.",
  stErrorHint: "Vérifiez checkpoint, CUDA et dépendances, puis redémarrez le connecteur.",
  stMismatchHint: "Cliquez sur « Charger ce modèle » pour passer à `{id}`.",
  stHost: "Sur",
  stOfflineHint: "Installez ou démarrez le connecteur (étapes sur cette fiche).",
  btnLoading: "Chargement…",
  btnUse: "Utiliser ce modèle",
  btnLoad: "Charger ce modèle",
  btnVerify: "Vérifier et utiliser",
  unselect: "Ne plus utiliser SAM",
  unselectHint: "Rien n’est désinstallé.",

  benchFps: "{fps} FPS vidéo",
  benchSam3: "Image de plus de 100 objets (benchmark Meta)",
  benchNone: "Aucun chiffre comparable",
  benchDisclaimer: "Référence officielle, pas une prévision pour votre GPU.",

  factCheckpoint: "checkpoint",
  factParams: "paramètres",
  factLicense: "licence",
  experimental: "Expérimental",
  capsHere: "Disponible ici",
  capsPending: "Le modèle le fait, l’éditeur pas encore",
  capsVideoNote: "Pas encore de vidéo : l’éditeur n’ouvre que des images.",
  citation: "Référence",
  readPaper: "Lire l’article",
  futureTitle: "{name} · bientôt",
  futureNote: "Pas encore disponible ici. Officiel : {speedup} sur {hardware}.",
  reqStack: "Logiciels",
  reqCompute: "Calcul",
  reqCuda: "CUDA",
  cudaRequired: "Obligatoire : CUDA {version}+",
  cudaOptional: "Facultatif ; GPU recommandé",
  cudaTested: " · testé : {version}",
  reqSystem: "Système",
  reqMemory: "Mémoire",
  reqAccess: "Accès",
  licenseWarning: "Licence et accès restreints",

  installTitle: "Installer",
  installBody: "Ne télécharge que le checkpoint choisi. Le premier modèle de chaque famille télécharge quelques Go de bibliothèques.",
  needsInstall: "{name} n’est pas installé.",
  needsInstallBody: "Lancez la commande ci-dessous et revenez.",
  osPicker: "Système d’exploitation",
  osUnix: "Linux ou macOS",
  osWsl: "Windows (WSL2)",
  osNative: "Windows",
  sam3NoMac: "SAM 3 exige CUDA : il ne tourne pas sous macOS.",
  sam3Native: "SAM 3 exige un GPU NVIDIA avec CUDA. L’installateur vérifie avant de télécharger.",
  download: "Télécharger {file}",
  stepDownloadTitle: "Téléchargez l’installateur",
  stepDownloadUnix: "Il va dans le dossier Téléchargements.",
  stepDownloadWin: "Il va dans le dossier Téléchargements.",
  stepUnixTerminalTitle: "Ouvrez le Terminal dans Téléchargements",
  stepUnixTerminalBody: "Ubuntu : Ctrl+Alt+T. macOS : Spotlight › Terminal.",
  stepUnixRunTitle: "Lancez l’installateur",
  stepUnixRunBody: "Il se termine par « installé, chargé et sélectionné ».",
  stepUnixKeepTitle: "Laissez le Terminal ouvert",
  stepUnixKeepBody: "Fermé ? L’IA s’arrête. Relancez avec le lanceur ci-dessous.",
  stepBackTitle: "Cliquez sur « Vérifier et utiliser »",
  stepBackBody: "L’état en bas passe au vert.",
  stepWslClickTitle: "Double-cliquez sur le fichier",
  stepWslClickBody: "Tapez le numéro du modèle et appuyez sur Entrée.",
  stepWslTypeTitle: "Ou par l’Invite de commandes",
  stepWslTypeBody: "Dans le dossier Téléchargements :",
  stepWslKeepTitle: "Laissez la fenêtre ouverte",
  stepWslKeepBody: "Fermée ? L’IA s’arrête.",
  stepNativeOpenTitle: "Ouvrez PowerShell",
  stepNativeOpenBody: "Depuis le menu Démarrer. Ne double-cliquez pas sur le fichier.",
  stepNativeFolderTitle: "Allez dans Téléchargements",
  stepNativeFolderBody: "",
  stepNativeRunTitle: "Lancez l’installateur",
  stepNativeRunBody: "Utilisez la commande complète.",
  stepNativeKeepTitle: "Laissez PowerShell ouvert",
  stepNativeKeepBody: "Fermé ? L’IA s’arrête.",
  cpuTitle: "CPU uniquement",
  cpuBody: "Pour ne pas utiliser la carte graphique, ou si elle est trop ancienne. Plus lent. Modifie les commandes ci-dessus.",
  relaunchTitle: "Pour relancer plus tard",
  relaunchUnix: "Utilisez le lanceur. Rien n’est retéléchargé.",
  relaunchService: "Sous Linux, le service relance tout seul à chaque connexion :",
  relaunchWsl: "Double-cliquez sur le lanceur. Rien n’est retéléchargé.",
  relaunchWslCpu: "Avec CPU coché, utilisez l’Invite de commandes :",
  relaunchNative: "Relancez la même commande.",
  sam3GpuOnly: "SAM 3 ne tourne que sur GPU NVIDIA.",
  oldGpuNote: "Carte trop ancienne ? L’installateur prévient avant de télécharger.",
  platformDetails: "Détails par système",
  uninstallTitle: "Désinstaller",
  uninstallBody: "Fermez le connecteur et supprimez le dossier ci-dessous. Rien ne reste ailleurs.",
  uninstallUnix: "Linux et macOS",
  uninstallNative: "Windows",
  uninstallWsl: "Windows (WSL2)",
  uninstallWslBody: "`wsl rm -rf ~/.poligome-sam`",
  uninstallService: "Linux avec le service : d’abord `poligome-sam-service-linux.sh uninstall`. Conteneurs BYOM : `docker rm -f`.",
  officialLinks: "Liens officiels",
  officialRepo: "Dépôt",
  officialCheckpoint: "Checkpoint",
  privacyTitle: "Confidentialité",
  samPrivacy: "Images et prompts restent sur l’ordinateur.",

  byomBadge: "Docker",
  byomTitle: "Ajouter mon modèle",
  byomIntro: "Votre modèle dans un conteneur Docker. Il reçoit l’image et renvoie des annotations COCO.",
  byomSagemaker: "Même contrat que SageMaker : commande `serve`, port 8080, `GET /ping` et `POST /invocations`. Poids dans `/opt/ml/model`.",
  byomBefore: "Avant de commencer",
  byomDockerTitle: "Docker en marche",
  byomDockerBody: "Poligome n’installe ni ne démarre Docker.",
  byomConnectorTitle: "Connecteur en marche",
  byomConnectorBody: "L’éditeur joint le conteneur via le connecteur. Installez-le depuis l’onglet Assisté.",
  byomWindowsTitle: "Sous Windows",
  byomWindowsBody: "Connecteur installé avec le `.bat` (WSL2) : utilisez la CLI bash dans WSL. Avec le `.ps1` : utilisez la CLI PowerShell.",
  byomContract: "Contrat",
  byomPort: "Port",
  byomPortValue: "`8080`",
  byomCommand: "Commande",
  byomHealth: "Prêt",
  byomHealthValue: "`GET /ping` → 200",
  byomInference: "Inférence",
  byomInferenceValue: "`POST /invocations` → COCO",
  byomWeights: "Poids",
  byomWeightsValue: "`/opt/ml/model`",
  byomDescription: "Description",
  byomDescriptionValue: "`GET /metadata` (facultatif)",
  byomInput: "Entrée :",
  byomInputValue: "`{ image, file_name, width, height }`",
  byomOutput: "Sortie :",
  byomOutputValue: "COCO. Chaque annotation doit avoir `segmentation` (liste de points, pas de RLE), `bbox` ou `keypoints`. `category_id` devient la classe.",
  byomErrors: "Erreurs :",
  byomErrorsValue: "`{ \"detail\": \"message\" }` — affiché à l’écran.",
  byomMetadataHint: "Avec `/metadata`, la fiche affiche les classes avant la première exécution.",
  byomFiles: "Fichiers",
  byomFilesBody: "Le serve.py d’exemple respecte déjà le contrat. Remplacez seulement la fonction predict().",
  byomCliUnix: "CLI · Linux, macOS, WSL2",
  byomCliNative: "CLI · Windows",
  byomCliNativeHint: "PowerShell",
  byomDockerfile: "Dockerfile",
  byomDockerfileHint: "exemple",
  byomServe: "serve.py",
  byomServeHint: "exemple",
  byomExamples: "Essayer les exemples",
  byomRepoTitle: "Avec le dépôt cloné",
  byomRepoBody: "Construit et enregistre deux modèles d’exemple (ports 8080 et 8081).",
  byomFilesOnlyTitle: "Avec seulement les fichiers téléchargés",
  byomFilesOnlyBody: "Construisez l’image et enregistrez les deux modèles :",
  byomCheckTitle: "Vérifier",
  byomCheckBody: "list affiche l’état ; logs affiche l’erreur.",
  byomSteps: "Pas à pas",
  byomStepsShell: "Commandes en bash. Sous Windows, utilisez `poligome-byom-windows.ps1` avec les mêmes commandes.",
  byomStep1Title: "1. Téléchargez les fichiers",
  byomStep1Body: "Remplacez la fonction predict() de serve.py par votre modèle.",
  byomStep1Comment: "# dossier des fichiers",
  byomStep2Title: "2. Construisez l’image",
  byomStep2Body: "",
  byomStep3Title: "3. Enregistrez",
  byomStep3Body: "L’identifiant commence par byom-.",
  byomStep4Title: "4. Démarrez",
  byomStep4Body: "Il apparaît dans la liste dès que /ping répond.",
  byomStep5Title: "5. Après un redémarrage",
  byomStep5Body: "Redémarrez-le. Pour démarrer avec Docker : docker update --restart unless-stopped.",
  byomImportTitle: "Importer un conteneur en marche",
  byomImportHint: "Enregistre seulement l’adresse. Le conteneur doit être actif.",
  byomFieldId: "Identifiant",
  byomFieldName: "Nom",
  byomFieldPort: "Port",
  byomNamePlaceholder: "Mon modèle",
  byomImporting: "Importation…",
  byomImport: "Importer",
  byomIdRule: "Commencez par `byom-` et n’utilisez que minuscules, chiffres, `.`, `-` ou `_`.",
  byomImportFailed: "Impossible d’importer : {detail}",
  byomNoneRegistered: "Aucun conteneur pour l’instant.",
  byomOneRegistered: "1 modèle enregistré.",
  byomManyRegistered: "{n} modèles enregistrés.",
  byomEmptyTitle: "Rien n’apparaît ?",
  byomEmptyBody: "Liste vide : connecteur arrêté. Modèle arrêté : voir `logs` (souvent un port occupé).",
  byomPrivacy: "Seulement `127.0.0.1` ou `localhost` : l’image ne quitte pas l’ordinateur.",
};

const es: SamCopy = {
  capImage: "Imagen",
  capVideo: "Vídeo",
  capPoints: "Puntos",
  capNegativePoints: "Puntos negativos",
  capBoxes: "Cajas",
  capMask: "Máscara anterior",
  capText: "Texto",
  capExemplars: "Ejemplos",
  capAutoMasks: "Máscaras automáticas",
  capMultimask: "Varias opciones",
  capRefine: "Refinamiento",
  capInstances: "Instancias",
  capConcepts: "Conceptos",
  capTracking: "Seguimiento",
  capMultiObject: "Varios objetos",
  capBidirectional: "Propagación en ambos sentidos",

  stChecking: "Buscando el conector…",
  stLoading: "Cargando el modelo…",
  stError: "El modelo no cargó",
  stReady: "Listo",
  stOtherLoaded: "Hay otro modelo cargado",
  stOffline: "Conector apagado",
  stSwitchRefused: "Cambio de modelo rechazado",
  stStillUp: "Sigue con {label}.",
  stErrorHint: "Revisa checkpoint, CUDA y dependencias, y reinicia el conector.",
  stMismatchHint: "Haz clic en «Cargar este modelo» para cambiar a `{id}`.",
  stHost: "En",
  stOfflineHint: "Instala o inicia el conector (pasos en esta ficha).",
  btnLoading: "Cargando…",
  btnUse: "Usar este modelo",
  btnLoad: "Cargar este modelo",
  btnVerify: "Comprobar y usar",
  unselect: "Dejar de usar SAM",
  unselectHint: "No se desinstala nada.",

  benchFps: "{fps} FPS en vídeo",
  benchSam3: "Imagen con más de 100 objetos (benchmark de Meta)",
  benchNone: "Sin cifra comparable",
  benchDisclaimer: "Referencia oficial, no una previsión para tu GPU.",

  factCheckpoint: "checkpoint",
  factParams: "parámetros",
  factLicense: "licencia",
  experimental: "Experimental",
  capsHere: "Disponible aquí",
  capsPending: "El modelo lo hace, el editor todavía no",
  capsVideoNote: "Sin vídeo por ahora: el editor solo abre imágenes.",
  citation: "Referencia",
  readPaper: "Leer el artículo",
  futureTitle: "{name} · próximamente",
  futureNote: "Todavía no disponible aquí. Oficial: {speedup} en {hardware}.",
  reqStack: "Software",
  reqCompute: "Procesamiento",
  reqCuda: "CUDA",
  cudaRequired: "Obligatorio: CUDA {version}+",
  cudaOptional: "Opcional; se recomienda GPU",
  cudaTested: " · probado: {version}",
  reqSystem: "Sistema",
  reqMemory: "Memoria",
  reqAccess: "Acceso",
  licenseWarning: "Licencia y acceso restringidos",

  installTitle: "Instalar",
  installBody: "Descarga solo el checkpoint elegido. El primer modelo de cada familia descarga algunos GB de bibliotecas.",
  needsInstall: "{name} no está instalado.",
  needsInstallBody: "Ejecuta el comando de abajo y vuelve.",
  osPicker: "Sistema operativo",
  osUnix: "Linux o macOS",
  osWsl: "Windows (WSL2)",
  osNative: "Windows",
  sam3NoMac: "SAM 3 exige CUDA: no funciona en macOS.",
  sam3Native: "SAM 3 exige GPU NVIDIA con CUDA. El instalador lo comprueba antes de descargar.",
  download: "Descargar {file}",
  stepDownloadTitle: "Descarga el instalador",
  stepDownloadUnix: "Va a la carpeta Descargas.",
  stepDownloadWin: "Va a la carpeta Descargas.",
  stepUnixTerminalTitle: "Abre la Terminal en Descargas",
  stepUnixTerminalBody: "Ubuntu: Ctrl+Alt+T. macOS: Spotlight › Terminal.",
  stepUnixRunTitle: "Ejecuta el instalador",
  stepUnixRunBody: "Termina con «instalado, cargado y seleccionado».",
  stepUnixKeepTitle: "Deja la Terminal abierta",
  stepUnixKeepBody: "¿La cerraste? La IA se apaga. Usa el lanzador de abajo para volver a encenderla.",
  stepBackTitle: "Haz clic en «Comprobar y usar»",
  stepBackBody: "El estado del pie se pone verde.",
  stepWslClickTitle: "Haz doble clic en el archivo",
  stepWslClickBody: "Escribe el número del modelo y pulsa Enter.",
  stepWslTypeTitle: "O desde el Símbolo del sistema",
  stepWslTypeBody: "En la carpeta Descargas:",
  stepWslKeepTitle: "Deja la ventana abierta",
  stepWslKeepBody: "¿La cerraste? La IA se apaga.",
  stepNativeOpenTitle: "Abre PowerShell",
  stepNativeOpenBody: "Desde el menú Inicio. No hagas doble clic en el archivo.",
  stepNativeFolderTitle: "Ve a la carpeta Descargas",
  stepNativeFolderBody: "",
  stepNativeRunTitle: "Ejecuta el instalador",
  stepNativeRunBody: "Usa el comando completo.",
  stepNativeKeepTitle: "Deja PowerShell abierto",
  stepNativeKeepBody: "¿Lo cerraste? La IA se apaga.",
  cpuTitle: "Solo CPU",
  cpuBody: "Para no usar la tarjeta gráfica, o si es demasiado antigua. Más lento. Cambia los comandos de arriba.",
  relaunchTitle: "Para volver a encender",
  relaunchUnix: "Usa el lanzador. No vuelve a descargar nada.",
  relaunchService: "En Linux, el servicio lo enciende solo en cada inicio de sesión:",
  relaunchWsl: "Doble clic en el lanzador. No vuelve a descargar nada.",
  relaunchWslCpu: "Con CPU marcado, usa el Símbolo del sistema:",
  relaunchNative: "Ejecuta el mismo comando otra vez.",
  sam3GpuOnly: "SAM 3 solo funciona en GPU NVIDIA.",
  oldGpuNote: "¿Tarjeta demasiado antigua? El instalador avisa antes de descargar.",
  platformDetails: "Detalles por sistema",
  uninstallTitle: "Desinstalar",
  uninstallBody: "Cierra el conector y borra la carpeta de abajo. No queda nada en otro lugar.",
  uninstallUnix: "Linux y macOS",
  uninstallNative: "Windows",
  uninstallWsl: "Windows (WSL2)",
  uninstallWslBody: "`wsl rm -rf ~/.poligome-sam`",
  uninstallService: "Linux con el servicio: antes, `poligome-sam-service-linux.sh uninstall`. Contenedores BYOM: `docker rm -f`.",
  officialLinks: "Enlaces oficiales",
  officialRepo: "Repositorio",
  officialCheckpoint: "Checkpoint",
  privacyTitle: "Privacidad",
  samPrivacy: "Imágenes y prompts se quedan en el ordenador.",

  byomBadge: "Docker",
  byomTitle: "Añadir mi modelo",
  byomIntro: "Tu modelo en un contenedor Docker. Recibe la imagen y devuelve anotaciones COCO.",
  byomSagemaker: "El mismo contrato que SageMaker: comando `serve`, puerto 8080, `GET /ping` y `POST /invocations`. Pesos en `/opt/ml/model`.",
  byomBefore: "Antes de empezar",
  byomDockerTitle: "Docker en marcha",
  byomDockerBody: "Poligome no instala ni inicia Docker.",
  byomConnectorTitle: "Conector en marcha",
  byomConnectorBody: "El editor llega al contenedor a través del conector. Instálalo desde la pestaña Asistido.",
  byomWindowsTitle: "En Windows",
  byomWindowsBody: "Conector instalado con el `.bat` (WSL2): usa la CLI bash dentro de WSL. Con el `.ps1`: usa la CLI de PowerShell.",
  byomContract: "Contrato",
  byomPort: "Puerto",
  byomPortValue: "`8080`",
  byomCommand: "Comando",
  byomHealth: "Listo",
  byomHealthValue: "`GET /ping` → 200",
  byomInference: "Inferencia",
  byomInferenceValue: "`POST /invocations` → COCO",
  byomWeights: "Pesos",
  byomWeightsValue: "`/opt/ml/model`",
  byomDescription: "Descripción",
  byomDescriptionValue: "`GET /metadata` (opcional)",
  byomInput: "Entrada:",
  byomInputValue: "`{ image, file_name, width, height }`",
  byomOutput: "Salida:",
  byomOutputValue: "COCO. Cada anotación necesita `segmentation` (lista de puntos, sin RLE), `bbox` o `keypoints`. `category_id` pasa a ser la clase.",
  byomErrors: "Errores:",
  byomErrorsValue: "`{ \"detail\": \"mensaje\" }` — se muestra en pantalla.",
  byomMetadataHint: "Con `/metadata`, la ficha muestra las clases antes de la primera ejecución.",
  byomFiles: "Archivos",
  byomFilesBody: "El serve.py de ejemplo ya cumple el contrato. Cambia solo la función predict().",
  byomCliUnix: "CLI · Linux, macOS, WSL2",
  byomCliNative: "CLI · Windows",
  byomCliNativeHint: "PowerShell",
  byomDockerfile: "Dockerfile",
  byomDockerfileHint: "ejemplo",
  byomServe: "serve.py",
  byomServeHint: "ejemplo",
  byomExamples: "Probar con los ejemplos",
  byomRepoTitle: "Con el repositorio clonado",
  byomRepoBody: "Crea y registra dos modelos de ejemplo (puertos 8080 y 8081).",
  byomFilesOnlyTitle: "Solo con los archivos descargados",
  byomFilesOnlyBody: "Construye la imagen y registra los dos modelos:",
  byomCheckTitle: "Comprobar",
  byomCheckBody: "list muestra el estado; logs muestra el error.",
  byomSteps: "Paso a paso",
  byomStepsShell: "Comandos en bash. En Windows, usa `poligome-byom-windows.ps1` con los mismos comandos.",
  byomStep1Title: "1. Descarga los archivos",
  byomStep1Body: "Cambia la función predict() de serve.py por tu modelo.",
  byomStep1Comment: "# carpeta de los archivos",
  byomStep2Title: "2. Construye la imagen",
  byomStep2Body: "",
  byomStep3Title: "3. Regístralo",
  byomStep3Body: "El identificador empieza por byom-.",
  byomStep4Title: "4. Inícialo",
  byomStep4Body: "Aparece en la lista cuando /ping responde.",
  byomStep5Title: "5. Tras reiniciar el ordenador",
  byomStep5Body: "Inícialo de nuevo. Para iniciarlo con Docker: docker update --restart unless-stopped.",
  byomImportTitle: "Importar un contenedor en marcha",
  byomImportHint: "Solo guarda la dirección. El contenedor tiene que estar activo.",
  byomFieldId: "Identificador",
  byomFieldName: "Nombre",
  byomFieldPort: "Puerto",
  byomNamePlaceholder: "Mi modelo",
  byomImporting: "Importando…",
  byomImport: "Importar",
  byomIdRule: "Empieza por `byom-` y usa solo minúsculas, números, `.`, `-` o `_`.",
  byomImportFailed: "No se pudo importar: {detail}",
  byomNoneRegistered: "Todavía no hay contenedores.",
  byomOneRegistered: "1 modelo registrado.",
  byomManyRegistered: "{n} modelos registrados.",
  byomEmptyTitle: "¿No aparece?",
  byomEmptyBody: "Lista vacía: conector apagado. Modelo detenido: mira `logs` (suele ser un puerto ocupado).",
  byomPrivacy: "Solo `127.0.0.1` o `localhost`: la imagen no sale del ordenador.",
};

const translations: Record<Language, SamCopy> = { pt, en, fr, es };

export function getSamCopy(language: Language): SamCopy {
  return translations[language];
}
